---
- name: Stop 3DIndex Service
  win_service: name="3DEXPERIENCE R2018x PICDaemonService" state=stopped
  tags: install-3dx-fp

- name: Copy UserIntention file to target
  template: src="templates/UserIntentions_3dx_fp.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_3dx_fp.xml"
  tags: install-3dx-fp
 
- name: Copy 3dx-ga installer from NFS to local
  win_copy:
    src: '{{ installer_path_fp }}'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: install-3dx-fp

- name: Executing platform FP installer
  win_command: '{{ windows_tmp_path }}\1\StartTUI.exe --silent {{ windows_tmp_path }}\UserIntentions_3dx_fp.xml --xmlreport {{ windows_tmp_path }}\Report_fp.xml'
  tags: install-3dx-fp

- name: Remove the user Intension file
  win_file: path="{{windows_tmp_path}}\UserIntentions_3dx_fp.xml" state=absent
  tags: install-3dx-fp

- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags: install-3dx-fp
