---

- name: Check if EntAVLManagement GA Apps installer path exists
  win_stat: path="{{ apps_GA_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-ga
     - component-central-ga
  
- name: EntAVLManagement GA Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - component-central-ga

- name: Copy EntAVLManagement GA UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_Component_central_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_Component_central_ga.xml"
  tags: 
     - install-app-ga
     - component-central-ga

- name: Copy EntAVLManagement GA apps installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\ENOVIAEnterpriseAVLManagement\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-ga
     - component-central-ga   
  
- name: Executing EntAVLManagement apps installation on target
  win_command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_ga_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_Component_central_ga.xml --xmlreport {{windows_tmp_path}}\Report_comp_cen.xml'
  tags: 
     - install-app-ga
     - component-central-ga

- name: Removing the user Intension file for EntAVLManagement from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_Component_central_ga.xml" state=absent
  tags: 
     - install-app-ga
     - component-central-ga

- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-ga
     - component-central-ga