---

- name: create the code backup dir or make sure it exist
  remote_user: monitor
  sudo: true
  file: path="{{ code_backup_dir }}" state=directory owner={{ plm_user }} group={{plm_group}} mode=0755
  tags: 
   - code-backup
   - install-mcs
   
- name: making tar of mcsnocas code
  shell:  tar -zcvf {{ code_backup_dir }}/{{ code_backup_filename }}.tar.gz mcsnocas mcscommon studio
  args:
    chdir: /{{ mcs_install_path }}
  tags:
    - code-backup
    - install-mcs
    
