---

     
- name: Copy the Connector for SolidWorks Server fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_conn_solidworksfx.j2" dest="{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ConnectorforSolidWorksServer.Unix64/1/answer_conn_solidworksfx.txt" mode=2777
  tags: 
     - install-solidworksfx
     - install-mcsfx

- name: Executing the Connector for SolidWorks Server fixpack  installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_conn_solidworksfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ConnectorforSolidWorksServer.Unix64/1
  tags: 
     - install-solidworksfx
     - install-mcsfx
   

- name: Remove the Connector for SolidWorks Server fixpack  Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ConnectorforSolidWorksServer.Unix64/1/answer_conn_solidworksfx.txt" state=absent
  tags: 
     - install-solidworksfx
     - install-mcsfx
