---
 

- name: Copy the Program Change Control fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_change_controlfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_controlfx.txt" mode=2777
  when: update_database
  tags: 
     - install-progchangefx
     - install-mcsfx


- name: Copy the Program Change Control fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_change_control_nudbfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_controlfx.txt" mode=2777
  when: not update_database
  tags: 
    - install-progchangefx
    - install-mcsfx


- name: Executing the Program Change Control fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_prog_change_controlfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAProgramChangeControl.Unix64/1
  tags: 
     - install-progchangefx
     - install-mcsfx
   

- name: Remove the Program Change Control fixpack Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_fp_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_controlfx.txt" state=absent
  tags: 
     - install-progchangefx
     - install-mcsfx

