---

- name: Copy the Engineering Central Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_eng_central.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAEngineeringCentral.Unix64/1/answer_eng_central.txt" mode=2777
  when: update_database
  tags: 
    - install-engcentral
    - install-mcs
   
- name: Copy the Engineering Central Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_eng_central_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAEngineeringCentral.Unix64/1/answer_eng_central.txt" mode=2777
  when: not update_database
  tags: 
     - install-engcentral
     - install-mcs

- name: Executing the Engineering Central installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_eng_central.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAEngineeringCentral.Unix64/1
  tags: 
     - install-engcentral
     - install-mcs
   

- name: Remove the Engineering Central answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAEngineeringCentral.Unix64/1/answer_eng_central.txt" state=absent
  tags: 
     - install-engcentral
     - install-mcs
