---
 

- name: Copy the CAPA and Audit Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_cap_audit_foundationfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIACAPAandAuditFoundation.Unix64/1/answer_cap_audit_foundationfx.txt" mode=2777
  when: update_database
  tags: 
     - install-capauditfx
     - install-mcsfx


- name: Copy the CAPA and Audit Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_cap_audit_foundation_nudbfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIACAPAandAuditFoundation.Unix64/1/answer_cap_audit_foundationfx.txt" mode=2777
  when: not update_database
  tags: 
    - install-capauditfx
    - install-mcsfx


- name: Executing the CAPA and Audit Foundation fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_cap_audit_foundationfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIACAPAandAuditFoundation.Unix64/1
  tags: 
     - install-capauditfx
     - install-mcsfx
   

- name: Remove the CAPA and Audit Foundation fixpack Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_fp_installer }}/ENOVIACAPAandAuditFoundation.Unix64/1/answer_cap_audit_foundationfx.txt" state=absent
  tags: 
     - install-capauditfx
     - install-mcsfx

