---
 
- name: Copy the Complians And NCR Foundation Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_comp_ncr_foundation.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAComplaintsandNCRFoundation.Unix64/1/answer_comp_ncr_foundation.txt" mode=2777
  when: update_database
  tags: 
    - install-compncr
    - install-mcs
   
- name: Copy the Complians And NCR Foundation Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_comp_ncr_foundation_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAComplaintsandNCRFoundation.Unix64/1/answer_comp_ncr_foundation.txt" mode=2777
  when: not update_database
  tags: 
     - install-compncr
     - install-mcs

- name: Executing the Complians And NCR Foundation installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_comp_ncr_foundation.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAComplaintsandNCRFoundation.Unix64/1
  tags: 
     - install-compncr
     - install-mcs
   

- name: Remove the Complians And NCR Foundation Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAComplaintsandNCRFoundation.Unix64/1/answer_comp_ncr_foundation.txt" state=absent
  tags: 
     - install-compncr
     - install-mcs

