---
 
- name: Copy the Program Experience Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_experience.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAProgramExperience.Unix64/1/answer_prog_experience.txt" mode=2777
  when: update_database
  tags: 
    - install-progexperience
    - install-mcs
    - install-apps-ga
   
- name: Copy the Program Experience Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_experience_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAProgramExperience.Unix64/1/answer_prog_experience.txt" mode=2777
  when: not update_database
  tags: 
     - install-progexperience
     - install-mcs
     - install-apps-ga

- name: Executing the Program Experience installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_prog_experience.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAProgramExperience.Unix64/1
  tags: 
     - install-progexperience
     - install-mcs
     - install-apps-ga
   

- name: Remove the Program Experience Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAProgramExperience.Unix64/1/answer_prog_experience.txt" state=absent
  tags: 
     - install-progexperience
     - install-mcs
     - install-apps-ga

