---

- name: Copy the CAD Design Foundation Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_caddes_foundation.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAX-CADDesignFoundation.Unix64/1/answer_caddes_foundation.txt" mode=2777
  tags: 
    - install-caddesign
    - install-mcs

- name: Executing the CAD Design Foundation installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_caddes_foundation.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAX-CADDesignFoundation.Unix64/1
  tags: 
     - install-caddesign
     - install-mcs
   

- name: Remove the CAD Design Foundation Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAX-CADDesignFoundation.Unix64/1/answer_caddes_foundation.txt" state=absent
  tags: 
    - install-caddesign
    - install-mcs


