---
 
- name: Copy the Collaboration for Microsoft Server Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_coll_microsoft_server.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1/answer_coll_microsoft_server.txt" mode=2777
  when: update_database
  tags: 
    - install-collmicrosrv
    - install-mcs
   
- name: Copy the Collaboration for Microsoft Server Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_coll_microsoft_server_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1/answer_coll_microsoft_server.txt" mode=2777
  when: not update_database
  tags: 
     - install-collmicrosrv
     - install-mcs

- name: Executing the Collaboration for Microsoft Server installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_coll_microsoft_server.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1
  tags: 
     - install-collmicrosrv
     - install-mcs
   

- name: Remove the Collaboration for Microsoft Server Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1/answer_coll_microsoft_server.txt" state=absent
  tags: 
     - install-collmicrosrv
     - install-mcs

