---
 
- name: Copy the BOM Configured Environment Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_bom_conf_env.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1/answer_bom_conf_env.txt" mode=2777
  when: update_database
  tags: 
    - install-bomconf
    - install-mcs
   
- name: Copy the BOM Configured Environment Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_bom_conf_env_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1/answer_bom_conf_env.txt" mode=2777
  when: not update_database
  tags: 
     - install-bomconf
     - install-mcs

- name: Executing the BOM Configured Environment installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_bom_conf_env.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1
  tags: 
     - install-bomconf
     - install-mcs
   

- name: Remove the BOM Configured Environment Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1/answer_bom_conf_env.txt" state=absent
  tags: 
     - install-bomconf
     - install-mcs

