---

- name: install the services
  remote_user: monitor
  sudo: true
  template: src="service.j2" dest="{{ service_dir }}/{{item.key}}" owner=root group=root mode="u=rwx,g=rx,o=rx"  
  with_dict: instances
  tags: 
    - deploy_service
    - install-mcs

- name: start services
  remote_user: monitor
  sudo: true
  service: name={{ item.key }} state=started enabled=yes
  with_dict: instances
  tags: 
    - deploy_service
    - install-mcs

