---

- name: Copy the Multi Discipline fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_multidis_collplatfx.j2" dest="{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1/answer_multidis_collplat.txt" mode=2777
  when: update_database
  tags: 
     - install-multidiscolfx
     - install-mcsfx
  
- name: Copy the Multi Discipline fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_multidis_collplatfx_nudb.j2" dest="{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1/answer_multidis_collplat.txt" mode=2777
  when: not update_database
  tags: 
     - install-multidiscolfx
     - install-mcsfx

- name: Executing the Multi Discipline fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_multidis_collplat.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1
  tags: 
     - install-multidiscolfx
     - install-mcsfx


- name: Remove the Multi Discipline fixpack Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1/answer_multidis_collplat.txt" state=absent
  tags: 
     - install-multidiscolfx
     - install-mcsfx