---
 
- name: Copy the Program Change Control Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_change_control.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_control.txt" mode=2777
  when: update_database
  tags: 
    - install-progchange
    - install-mcs
    - install-apps-ga
   
- name: Copy the Program Change Control Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_change_control_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_control.txt" mode=2777
  when: not update_database
  tags: 
     - install-progchange
     - install-mcs
     - install-apps-ga

- name: Executing the Program Change Control installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_prog_change_control.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAProgramChangeControl.Unix64/1
  tags: 
     - install-progchange
     - install-mcs
     - install-apps-ga
   

- name: Remove the Program Change Control Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAProgramChangeControl.Unix64/1/answer_prog_change_control.txt" state=absent
  tags: 
     - install-progchange
     - install-mcs
     - install-apps-ga

