---
 

- name: Copy the Program Central Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_cen_foundationfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_prog_cen_foundationfx.txt" mode=2777
  when: update_database
  tags: 
     - install-progcentralfx
     - install-mcsfx


- name: Copy the Program Central Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_prog_cen_foundation_nudbfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_prog_cen_foundationfx.txt" mode=2777
  when: not update_database
  tags: 
    - install-progcentralfx
    - install-mcsfx


- name: Executing the Program Central Foundation fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_prog_cen_foundationfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1
  tags: 
     - install-progcentralfx
     - install-mcsfx
   

- name: Remove the Program Central Foundation fixpack Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_prog_cen_foundationfx.txt" state=absent
  tags: 
     - install-progcentralfx
     - install-mcsfx

