---
 
- name: Copy the Microsoft Project Integration Server Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_micro_proj_intrsrv.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1/answer_micro_proj_intrsrv.txt" mode=2777
  when: update_database
  tags: 
    - install-microproj
    - install-mcs
   
- name: Copy the Microsoft Project Integration Server Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_micro_proj_intrsrv_nudb.j2" dest="{{ mcs_apps_ga_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1/answer_micro_proj_intrsrv.txt" mode=2777
  when: not update_database
  tags: 
     - install-microproj
     - install-mcs

- name: Executing the Microsoft Project Integration Server installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_micro_proj_intrsrv.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1
  tags: 
     - install-microproj
     - install-mcs
   

- name: Remove the Microsoft Project Integration Server Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_ga_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1/answer_micro_proj_intrsrv.txt" state=absent
  tags: 
     - install-microproj
     - install-mcs

