---
 

- name: Copy the Library Central fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_lib_centralfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_lib_centralfx.txt" mode=2777
  when: update_database
  tags: 
     - install-reqcentralfx
     - install-mcsfx


- name: Copy the Library Central fixpack Answer file to Installer Directory
  remote_user: monitor
  sudo: true
  template: src="answer_lib_central_nudbfx.j2" dest="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_lib_centralfx.txt" mode=2777
  when: not update_database
  tags: 
    - install-reqcentralfx
    - install-mcsfx


- name: Executing the Library Central fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < answer_lib_centralfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1
  tags: 
     - install-reqcentralfx
     - install-mcsfx
   

- name: Remove the Library Central fixpack Answer file
  remote_user: monitor
  sudo: true
  file: path="{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1/answer_lib_centralfx.txt" state=absent
  tags: 
     - install-reqcentralfx
     - install-mcsfx

