---

- name: create the ssl dir or make sure it exist
  file: path="{{ ssl_directory }}" state=directory owner=root group=root mode=2755
  tags: 
    - deploy-vhost
    - install-reverseproxy

- name: Generate RSA key(private key)
  command: openssl genrsa -out {{ ssl_directory }}/{{ item }}.key {{ ssl_certs_key_size }} creates={{ ssl_directory }}/{{ item }}.key
  with_items: ssl_certs
  tags: 
    - generate-cert
    - install-reverseproxy

- name: Generate CSR
  command: openssl req -new -subj "{{ ssl_certs_fields }}" -key {{ ssl_directory }}/{{ item }}.key -out {{ ssl_directory }}/{{ item }}.csr creates={{ ssl_directory }}/{{ item }}.csr
  with_items: ssl_certs
  tags: 
    - generate-cert
    - install-reverseproxy
  
- name: Generate Crt
  command: openssl x509 -req -days 365 -in {{ ssl_directory }}/{{ item }}.csr -signkey {{ ssl_directory }}/{{ item }}.key -out {{ ssl_directory }}/{{ item }}.crt
  with_items: ssl_certs
  tags: 
    - generate-cert
    - install-reverseproxy