---

- name: Update MATRIX-R file
  blockinfile:
    dest: "{{ r15x_conf_dir }}/MATRIX-R"
    create: no
    insertafter: "EncryptionVersion=10"
    block: |
      {{ db2_jdbc_url }}
  tags: 
     - update-jdbc-url
    
    
- name: Check NewTypingMigration.jar exits or not
  stat: path={{r15x_server_dir}}/linux_a64/docs/javaserver/NewTypingMigration.jar
  register: file_stat
  tags:
    - deploy-newtyping-rnd-fix
    - effective_migration

- name: Rename NewTypingMigration.jar
  command: mv {{r15x_server_dir}}/linux_a64/docs/javaserver/NewTypingMigration.jar {{r15x_server_dir}}/linux_a64/docs/javaserver/NewTypingMigration.jar.old
  when: file_stat.stat.exists
  tags:
    - deploy-newtyping-rnd-fix
    - effective_migration
  
  
- name: Check SRChecker.jar exits or not
  stat: path={{r15x_server_dir}}/linux_a64/docs/javaserver/SRChecker.jar
  register: file_stat
  tags:
    - deploy-newtyping-rnd-fix
    - effective_migration

- name: Rename NewTypingMigration.jar
  command: mv {{r15x_server_dir}}/linux_a64/docs/javaserver/SRChecker.jar {{r15x_server_dir}}/linux_a64/docs/javaserver/SRChecker.jar.old
  when: file_stat.stat.exists
  tags:
    - deploy-newtyping-rnd-fix
    - effective_migration
     
    
    
- name: Copy the SRChecker.jar from NFS
  synchronize:
      src: "{{mount_dest_dir}}/sources/dsproducts/enoviav6/r2015x/server-side/3dspace/fp1616/fixes/SR00377995/PinPoints/CP0131V6R2015xT14PP6.AllOS/1/linux_a64/docs/javaserver/" 
      dest: "{{r15x_server_dir}}/linux_a64/docs/javaserver/"
      checksum: yes
      recursive: yes
      archive: no
  delegate_to: "{{inventory_hostname}}"
  tags: 
    - deploy-newtyping-rnd-fix
    - copy_pinpoint_jar
    - effective_migration
    

- name: Copy the  NewTypingMigration.jar from NFS to lib path
  synchronize:
      src: "{{mount_dest_dir}}/sources/dsproducts/enoviav6/r2015x/server-side/3dspace/fp1616/fixes/SR00377995/PinPoints/CP0131V6R2015xT14PP6.AllOS/1/linux_a64/docs/javaserver/NewTypingMigration.jar"  
      dest: "{{r15x_server_dir}}/STAGING/ematrix/WEB-INF/lib/NewTypingMigration.jar"
      checksum: yes
      recursive: yes
      archive: no
  delegate_to: "{{inventory_hostname}}"
  tags: 
    - deploy-newtyping-rnd-fix
    - effective_migration    
    
- name: Copy the  NewTypingMigration.jar from NFS to classes path
  synchronize:
      src: "{{mount_dest_dir}}/sources/dsproducts/enoviav6/r2015x/server-side/3dspace/fp1616/fixes/SR00377995/PinPoints/CP0131V6R2015xT14PP6.AllOS/1/linux_a64/docs/javaserver/NewTypingMigration.jar"  
      dest: "{{r15x_server_dir}}/STAGING/ematrix/classes/NewTypingMigration.jar"
      checksum: yes
      recursive: yes
      archive: no
  delegate_to: "{{inventory_hostname}}"
  tags: 
    - deploy-newtyping-rnd-fix
    - effective_migration    

    
- name: create the r15x newtyping log dir
  file: path="{{ r15x_newtype_log_dir_all }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=0755
  tags: 
    - newtyping-genalltype    
    
    
- name: Run the emxNewTypingMigrationProgram script for all type
  shell: nohup time ./mql -c "set context user creator password creator.; exec prog emxNewTypingMigrationProgram -dir {{r15x_newtype_log_dir_all}} -GenAllFiles;quit;" 2>&1 > {{r15x_server_dir}}/logs/mql-emxNewTypingMigrationProgram_AllType.txt &
  args:
    chdir: /{{ r15x_server_script_dir }}
  tags:
    - newtyping-genalltype

    
- name: create the r15x newtyping log dir
  file: path="{{ r15x_newtype_log_dir_notall }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=0755
  tags: 
    - newtyping-gennotalltype


- name: Run the emxNewTypingMigrationProgram script for limited type
  shell: nohup time ./mql -c "set context user creator password creator.; exec prog emxNewTypingMigrationProgram -dir {{r15x_newtype_log_dir_notall}} -GenFiles;quit;" 2>&1 > {{r15x_server_dir}}/logs/mql-emxNewTypingMigrationProgram_limitedType.txt &
  args:
    chdir: /{{ r15x_server_script_dir }}
  tags:
    - newtyping-gennotalltype
