---

- name: Check if Apps installer path exists
  win_stat: path="{{apps_FP_installer_path}}\ENOVIA3DLiveExamine\1"
  register: check_apps_path
  tags: 
     - install-app-fp
     - ENOVIA3DLiveExamine-fp
  
- name: Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-fp
     - ENOVIA3DLiveExamine-fp

- name: Copy 3DLive UserIntention file to target
  template: src="templates/user_intention_apps/fp/UserIntentions_3dlive_fp.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_3dlive_fp.xml"
  tags: 
     - install-app-fp
     - ENOVIA3DLiveExamine-fp

- name: Copy GA-Platform installer from NFS to local
  win_copy:
    src: '{{apps_FP_installer_path}}\ENOVIA3DLiveExamine\1'
    dest: '{{ windows_tmp_path }}\ENOVIA3DLiveExamine'
    remote_src: True
  tags: 
    - install-app-fp
    - ENOVIA3DLiveExamine-fp
  
- name: Executing 3DLive installation on target
  win_psexec:
    command: '{{windows_tmp_path}}\ENOVIA3DLiveExamine\1\StartTUI.exe -installerPath {{ds_fp_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_3dlive_fp.xml --xmlreport {{windows_tmp_path}}\Report_3dLive_fp.xml'
    elevated: yes
  tags: 
     - install-app-fp
     - ENOVIA3DLiveExamine-fp

- name: Removing the user Intension file for 3DLive from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_3dlive_fp.xml" state=absent
  tags: 
     - install-app-fp
     - ENOVIA3DLiveExamine-fp
     
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\ENOVIA3DLiveExamine" state=absent
  tags:  
     - install-app-fp
     - ENOVIA3DLiveExamine-fp