---

- name: Check if Apps installer path exists
  win_stat: path="{{ apps_GA_installer_path }}\ENOVIA3DLiveExamine\1"
  register: check_apps_path
  tags: 
     - install-app-ga
     - ENOVIA3DLiveExamine
  
- name: Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - ENOVIA3DLiveExamine

- name: Copy 3DLive UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_3dlive_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_3dlive_ga.xml"
  tags: 
     - install-app-ga
     - ENOVIA3DLiveExamine

- name: Copy GA-Platform installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\ENOVIA3DLiveExamine\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: install-platform-ga   
  
- name: Executing 3DLive installation on target
  win_psexec: 
      command: '{{windows_tmp_path}}\ENOVIA3DLiveExamine\1\StartTUI.exe -installerPath {{ds_ga_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_3dlive_ga.xml --xmlreport {{windows_tmp_path}}\Report_3dLive_ga.xml'
  tags: 
     - install-app-ga
     - ENOVIA3DLiveExamine

- name: Removing the user Intension file for 3DLive from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_3dlive_ga.xml" state=absent
  tags: 
     - install-app-ga
     - ENOVIA3DLiveExamine
     
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-ga
     - ENOVIA3DLiveExamine-ga

