---

- name: Create the database
  remote_user: monitor
  become: true
  mysql_db: name={{ item.name }} state=present login_user=root login_password={{ mysql_root_db_pass }}
  with_items: '{{mysql_db}}'
  when: mysql_db|lower() != 'none'
  tags:
     - create-pass-database
     - install-mysql

- name: Create the database users
  remote_user: monitor
  become: true
  mysql_user: name={{ item.name }}  password={{ item.pass }}
                priv={{ item.priv }} state=present host={{ item.host | default("localhost") }} append_privs=yes login_user=root login_password={{ mysql_root_db_pass }}
  with_items: '{{mysql_users}}'
  when: mysql_users|lower() != 'none'
  tags:
     - create-pass-database
     - install-mysql
     - append-privilege
     
     
- name: Create 3ddashboard database
  remote_user: monitor
  become: true
  mysql_db: name={{ item.name }} state=present login_user=root login_password={{ mysql_root_db_pass }}
  with_items: '{{mysql_dash_db}}'
  when: mysql_dash_db|lower() != 'none'
  tags:
     - create-dash-database


- name: Create the database users for locathost
  remote_user: monitor
  become: true
  mysql_user: name={{ item.name }}  password={{ item.pass }}
                priv={{ item.priv }} state=present host="localhost" login_user=root login_password={{ mysql_root_db_pass }}
  with_items: '{{mysql_dash_users}}'
  when: mysql_dash_users|lower() != 'none'
  tags:
     - create-dash-database
     
- name: Create the database users for %
  remote_user: monitor
  become: true
  mysql_user: name={{ item.name }}  password={{ item.pass }}
                priv={{ item.priv }} state=present host={{ item.host | default("localhost") }} login_user=root login_password={{ mysql_root_db_pass }}
  with_items: '{{mysql_dash_users}}'
  when: mysql_dash_users|lower() != 'none'
  notify: restart mysql 
  tags:
     - create-dash-database
