---

- name: install mysql packages
  yum: name={{item}} state=installed
  with_items: mysql_pkgs
  tags:
     - install-mysql

- name: install mysql-client
  yum: name=mysql state=installed
  tags:
     - install-mysql-client

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify: restart mysql
  tags: install-mysql

- name: Create the directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify: restart mysql
  tags: install-mysql
  
- name: Start the mysql services
  service: name={{ mysql_service }} state=started enabled=yes
  tags:
     - install-mysql

- name: update mysql root password for all root accounts
  mysql_user: login_user=root 
              login_password={{ mysql_current_pass }}
              name=root host={{ item }} 
              password={{ mysql_root_db_pass }}
              priv=*.*:All,GRANT
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost' and mysql_root_password_update
  tags:
     - install-mysql
     - update-rootpass
     - uninstall-passport
     
- name: update mysql root password for all root accounts
  mysql_user: login_user=root
              login_password={{ mysql_current_pass }}
              name=root
              host={{ item }}
              password={{ mysql_root_db_pass }}
              priv=*.*:All,GRANT
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'  and mysql_root_password_update
  tags:
     - install-mysql
     - update-rootpass
     - uninstall-passport

- name: copy .my.cnf file with root password credentials
  template: src=client.cnf.j2 dest=~/.my.cnf mode=0600
  tags:
     - install-mysql
     - uninstall-passport







     




