---

- name: JAVA8 - GET JAVA8 DIRECTORY
  remote_user: monitor
  become: true
  command: find {{ passport_soft_dir }} -maxdepth 1 -type d ! -path {{ passport_soft_dir }} -iname "jdk1.8*" 
  register: directoryJDK
  tags: install-passport-fp

- name: JAVA8 - LINKING
  remote_user: monitor
  become: true
  file: src={{ directoryJDK.stdout }} dest={{ passport_jdk_path }} state=link owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw" 
  tags: install-passport-fp
  
- name: Check if fixpack installer path exists
  remote_user: "{{ plm_user }}"
  stat: path="{{passport_installer_path}}/{{ fix_pack_version }}/X3D_PASS.Linux64"
  register: check_path
  tags:
    - install-passport-fp

- name: Installer doesn't exist
  remote_user: "{{ plm_user }}"
  fail: msg="3DPassport fixpack installer doesn't exist!!"
  when: not check_path.stat.exists
  tags:
    - install-passport-fp
    
- name: Ensure '/var/DassaultSystemes' folder exist
  remote_user: monitor
  become: true
  file:
      path: "{{ passport_dir_var }}"
      state: directory
      owner: "{{ plm_user }}"
      group: "{{ plm_group }}"
      mode: "755"
  tags: 
    - install-passport-fp
    
 
- name: Copy the answer file to Installer Directory
  remote_user: "{{ plm_user }}"
  template: src="answer_fp.j2" dest="{{passport_conf_dir}}/answer_fp.txt" mode=2777
  tags: 
    - install-passport-fp

- name: Executing the fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{passport_conf_dir}}/answer_fp.txt
  args:
    chdir: /{{passport_installer_path}}/{{fix_pack_version}}/X3D_PASS.Linux64/1
  tags: 
    - install-passport-fp

- name: Remove the fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{passport_conf_dir}}/answer_fp.txt" state=absent
  tags: 
    - install-passport-fp
  
