---

- name: wait for deploy war
  remote_user: "{{ plm_user }}"
  wait_for: path="{{tomcat_webapp_dir}}/{{web_app_name}}/WEB-INF/spring-configuration/applicationContext-aspects.xml"
  tags: 
    - post-install
    - install-passport-fp
    
    
- name: Updating the Configuration in applicationContext-aspects.xml
  remote_user: monitor
  become: true
  template: src="appContext-aspects.xml.j2" dest="{{tomcat_webapp_dir}}/{{web_app_name}}/WEB-INF/spring-configuration/applicationContext-aspects.xml" owner={{plm_user }} group={{ plm_group }}
  tags: 
    - post-install
    - install-passport-fp
    - update-appcontext