---

- name: Stop Tomcat instances.
  remote_user: monitor
  become: true
  command: service {{ item.key }} stop
  with_dict: "{{ instances }}"
  tags: 
   - uninstall-passport
   - stop-tomcat-instance
   
   
- name: Remove the 3DPassport dir
  remote_user: monitor
  become: true
  file: path="{{ passport_install_rel_path }}" state=absent owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - uninstall-passport
   