---


- name: 3dcomment vhost deploy
  template: src="3dcomment.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3dcomment.conf"
  tags:
    - deploy-vhost


- name: 3ddashboard vhost deploy
  template: src="3ddashboard.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3ddashboard.conf"
  tags: 
    - deploy-vhost
    

- name: 3dnotification vhost deploy
  template: src="3dnotification.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3dnotification.conf"
  tags: 
    - deploy-vhost
  

- name: 3dpassport vhost deploy
  template: src="3dpassport.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3dpassport.conf"
  tags: 
    - deploy-vhost
 
 
- name: 3dspace vhost deploy
  template: src="3dspace.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3dspace.conf"
  tags: 
    - deploy-vhost


- name: 3dswym vhost deploy
  template: src="3dswym.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-3dswym.conf"
  tags: 
    - deploy-vhost


- name: fcscentral vhost deploy
  template: src="fcscentral.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-fcscentral.conf"
  tags: 
    - deploy-vhost


- name: fedsearch vhost deploy
  template: src="fedsearch.conf.j2" dest="{{ vhost_path }}\{{ env_name }}-fedsearch.conf"
  tags: 
    - deploy-vhost
    

- name: Update 'httpd conf' file 
  win_lineinfile:
    path: '{{ where_to_install }}/conf/httpd.conf'
    state: present
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  with_items:
    - line: Include {{ vhost_path }}\{{ env_name }}-3dspace.conf
      insertafter: </IfModule>
    - line: Include {{ vhost_path }}\{{ env_name }}-3dpassport.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-3dspace.conf
    - line: Include {{ vhost_path }}\{{ env_name }}-3ddashboard.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-3dpassport.conf
    - line: Include {{ vhost_path }}\{{ env_name }}-3dcomment.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-3ddashboard.conf
    - line: Include {{ vhost_path }}\{{ env_name }}-3dswym.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-3dcomment.conf
    - line: Include {{ vhost_path }}\{{ env_name }}-fedsearch.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-3dswym.conf
    - line: Include {{ vhost_path }}\{{ env_name }}-fcscentral.conf
      insertafter: Include {{ vhost_path }}\{{ env_name }}-fedsearch.conf
    

  tags: 
    - deploy-httpdcon
    - deploy-vhost
