---

- name: create symbolic link for the java 8 path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ studio_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - install-studiofx
    
    
- name: Check if studio fixpack installer path exists
  remote_user: "{{ plm_user }}"
  stat: path="{{studio_fp_installer_path}}"
  register: check_path
  tags: install-studiofx


- name: Studio fixpack installer doesn't exist
  remote_user: "{{ plm_user }}"
  fail: msg="studio fixpack installer doesn't exist!!"
  when: not check_path.stat.exists
  tags: install-studiofx
  
  
- name: Copy the Studio Modeling Platform RichClients fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_studiofx.j2" dest="{{ studio_conf_dir }}/answer_studiofx.txt" mode=2777
  tags: install-studiofx


- name: Executing the Studio Modeling Platform RichClients fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh < {{ studio_conf_dir }}/answer_studiofx.txt
  args:
    chdir: /{{ studio_fp_installer_path }}/1
  tags: install-studiofx
  

- name: Remove the Studio Modeling Platform RichClients fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ studio_conf_dir }}/answer_studiofx.txt" state=absent
  tags: install-studiofx
  
  
- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ studio_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - install-studiofx
