---

- name: Check if SolidWorks GA Apps installer path exists
  win_stat: path="{{apps_GA_installer_path}}\ConnectorforSolidWorksServer\1"
  register: check_apps_path
  tags: 
     - install-app-ga
     - solidworks-ga
  
- name: SolidWorks GA Apps  installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - solidworks-ga

- name: Copy SolidWorks GA Apps UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_Solidworks_conn_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_Solidworks_conn_ga.xml"
  tags: 
     - install-app-ga
     - solidworks-ga

- name: Copy SolidWorks GA Apps installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\\ConnectorforSolidWorksServer\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-ga
     - solidworks-ga
  
- name: Executing SolidWorks GA Apps installation on target
  win_command: '{{apps_GA_installer_path}}\ConnectorforSolidWorksServer\1\StartTUI.exe -installerPath {{ds_fp_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_Solidworks_conn_ga.xml --xmlreport {{windows_tmp_path}}\Report_Solidworks_GA.xml'
  tags: 
     - install-app-ga
     - solidworks-ga

- name: Removing the user Intension file for SolidWorks GA Apps from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_Solidworks_conn_ga.xml" state=absent
  tags: 
     - install-app-ga
     - solidworks-ga
     
- name: Removing the user SolidWorks GA Apps report from traget
  win_file: path="{{windows_tmp_path}}\Report_Solidworks_GA.xml" state=absent
  tags: 
     - install-app-ga
     - solidworks-ga
     
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags: 
     - install-app-ga
     - solidworks-ga