- name: Firing -> Run test script for 3ddash
  win_command: '{{ TARGET_PATH }}\win_b64\code\command\run_test.bat'
  register: outputListCommand
  tags: 
     - run_test
- name: Printing -> Run test output for 3ddash
  debug: msg={{ outputListCommand  }}
  tags: 
     - run_test