---

- name: Check if DMA FP Apps installer path exists
  win_stat: path="{{ apps_FP_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-fp
     - DMA-fp
  
- name: DMA FP Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-fp
     - DMA-fp

- name: Copy DMC GA UserIntention file to target
  template: src="templates/user_intention_apps/fp/UserIntentions_DMA_fp.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_DMA_fp.xml"
  tags: 
     - install-app-fp
     - DMA-fp

- name: Copy DMC FP apps installer from NFS to local
  win_copy:
    src: '{{ apps_FP_installer_path }}\DataModelCustomizationFoundation.Windows64\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-fp
     - DMA-fp
  
- name: Executing DMA FP installation on target
  win_command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_fp_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_DMA_fp.xml --xmlreport {{windows_tmp_path}}\Report_DMA_fp.xml'
  tags: 
     - install-app-fp
     - DMA-fp

- name: Removing the user Intension file for DMA from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_DMA_fp.xml" state=absent
  tags: 
     - install-app-fp
     - DMA-fp
     
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-fp
     - DMA-fp

