---

- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ system_apps_dir }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-3dx

- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ eplm_server_base_path }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-3dx

- name: create the 3dx Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_rel_path }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx
   
- name: create the code Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_install_path }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx  
   
- name: create the plug-in Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_plugin_dir }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx  
   
- name: create the managed Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_plugin_dir }}/managed/properties" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx 
   
- name: create the STAGING Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_plugin_dir }}/STAGING/ematrix/WEB-INF/classes" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx 
   
   
- name: create the index Directory or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_index_dir }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
   - create_dirs
   - install-3dx  
   
   
- name: create the bin or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_bin_dir }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
    - create_dirs
    - install-3dx 
    

- name: create the log or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ e3dx_logdir }}" state=directory owner={{plm_user}}  group={{plm_group}} mode=2755
  tags: 
    - create_dirs
    - install-3dx