---

- name: Check if 3dx fixpack installer path exists
  remote_user: "{{ plm_user }}"
  stat: path="{{ e3dx_fixpack_installer }}"
  register: check_path
  tags: install-3dx-fp


- name: 3dx fixpack installer doesn't exist
  remote_user: "{{ plm_user }}"
  fail: msg="3dx fixpack installer doesn't exist!!"
  when: not check_path.stat.exists
  tags: install-3dx-fp
   
   
- name: Copy 3dx fixpack answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_fixpack.j2" dest="{{ e3dx_rel_path }}/answer.txt" mode=2777
  tags: 
   - install-3dx-fp

- name: Executing the 3dx fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh < {{ e3dx_rel_path }}/answer.txt
  args:
    chdir: /{{ e3dx_fixpack_installer }}/1  
  tags: 
   - install-3dx-fp
   

- name: remove the 3dx answer file
  remote_user: monitor
  become: true
  file: path="{{ e3dx_rel_path }}/answer.txt" state=absent
  tags: 
   - install-3dx-fp