---

- name: check iptables not running
  remote_user: monitor
  become: true
  shell: service iptables status | grep not | awk '{ print $4 }'
  register: iptables_stoped
  tags:
   - config-firewall
   - install-3dx-fp
   
   
- name: Allow HTTP ports to 3dx server
  remote_user: monitor
  become: true
  command: iptables -A INPUT -p tcp --match multiport --dports 58000:58006 -j ACCEPT
  when: "'not' not in iptables_stoped.stdout"
  tags:
   - config-firewall
   - install-3dx-fp
   
   
- name: Allow HTTP ports to 3dx http server
  remote_user: monitor
  become: true
  command: iptables -I INPUT -p tcp -m tcp --dport 8091 -j ACCEPT
  when: "'not' not in iptables_stoped.stdout"
  tags:
   - config-firewall
   - install-3dx-fp   


- name: save iptables
  remote_user: monitor
  become: true
  command: service iptables save
  when: "'not' not in iptables_stoped.stdout" 
  tags:
   - config-firewall
   - install-3dx-fp
  