---
- name: create the base dir or make sure it exist
  remote_user: monitor
  sudo: true
  file: path="{{ system_apps_dir }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs
   - install-studio
    
- name: create the base dir or make sure it exist
  remote_user: monitor
  sudo: true
  file: path="{{ eplm_server_base_path }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs  
   - install-studio

- name: create symbolic link
  remote_user: monitor
  sudo: true
  file: src="{{ eplm_server_base_path }}" dest="/plm" state=link owner=root group=root mode=2777
  tags: 
  - create_dirs
  - install-studio

- name: create the apps env
  remote_user: monitor
  sudo: true
  file: path="{{ studio_env_path }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs
   - install-studio

- name: create the studio dir
  remote_user: monitor
  sudo: true
  file: path="{{ studio_install_path }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-studio
   
   
- name: create the code dir or make sure it exist
  remote_user: monitor
  sudo: true
  file: path="{{ studio_code_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-studio
   
   
- name: create the conf dir or make sure it exist
  remote_user: monitor
  sudo: true
  file: path="{{ studio_conf_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-studio
  
    
- name: create the soft dir for JDK
  remote_user: monitor
  sudo: true
  file: path="{{ studio_soft_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  tags: 
    - create_dirs
    - install-studio

- name: create the dir for mcs logs
  remote_user: monitor
  sudo: true
  file: path="{{ studio_log_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=r"
  tags: 
    - create_dirs
    - install-studio

