---

- name: Generate Matrix-R file
  shell: ./mql -install -user {{db2_connection_user}} -password {{db2_connection_user_pass}} -host {{db2_database_name}} -driver 'DB2/CLI' -tablespace {{db2_data_tablespace}} -indexspace {{db2_index_tablespace}}
  args:
    chdir: /{{ studio_code_dir }}/scripts
  ignore_errors: yes
  tags: 
    - generate-matrix
    - install-studio
    
- name: Check if Matrix-R file generate or not
  stat: path="{{studio_conf_dir}}/Matrix-R"
  register: check_file
  tags: 
    - generate-matrix
    - install-studio
    - nnn

- name: Matrix-R doesn't exist
  fail: msg="Matrix-R doesn't exist!!"
  when: check_file.stat.exists == True
  tags: 
    - generate-matrix
    - install-studio
    - nnn
