---

- name: Check if java path exists or not
  stat: path="{{ studio_java_path }}"
  register: check_path
  tags: 
   - install-java  
   - install-studio

- name: untar jdk inside instance
  remote_user: monitor
  sudo: true
  unarchive: src="{{installer_path}}/{{java_installer}}" dest="{{ studio_soft_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  when: not check_path.stat.exists
  tags: 
   - install-java  
   - install-studio
   
- name: get java path
  shell: ls {{ studio_soft_dir }}
  register: dir_content
  when: not check_path.stat.exists
  tags: 
   - install-java  
   - install-studio
   
- name: create symbolic link for the java path
  remote_user: monitor
  sudo: true
  file: src="{{ dir_content.stdout }}" dest="{{ studio_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  when: not check_path.stat.exists
  tags: 
   - install-java  
   - install-studio
