#- include: prerequisite.yml
- include: 3dspaceIndex_installation_ga.yml
- include: 3dspaceIndex_installation_fp.yml
#- include: restart_service.yml
- include: restart_service.yml
- include: run_test.yml
- include: copy_installer_local.yml
