---

- name: Check if AutoCAD GA Apps installer path exists
  win_stat: path="{{ apps_GA_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-ga
     - AutoCad-ga
  
- name: AutoCAD GA Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - AutoCad-ga

- name: Copy AutoCAD GA UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_Autocad_conn_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_AutoCAD_GA.xml"
  tags: 
     - install-app-ga
     - AutoCad-ga

- name: Copy AutoCAD GA apps installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\ConnectorforAutoCADServer\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-ga
     - AutoCad-ga 
  
- name: Executing AutoCAD apps installation on target
  win_command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_ga_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_AutoCAD_GA.xml --xmlreport {{windows_tmp_path}}\Report_AutoCAD_GA.xml'
  tags: 
     - install-app-ga
     - AutoCad-ga

- name: Removing the user Intension file for AutoCAD from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_AutoCAD_GA.xml" state=absent
  tags: 
     - install-app-ga
     - AutoCad-ga
     
- name: Removing the user Intension file for AutoCAD from traget
  win_file: path="{{windows_tmp_path}}\Report_AutoCAD_GA.xml" state=absent
  tags: 
     - install-app-ga
     - AutoCad-ga

- name: Remove the AutoCAD installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-ga
     - AutoCad-ga