---

- name: Check if AutoCAD FP Apps installer path exists
  win_stat: path="{{apps_FP_installer_path}}"
  register: check_apps_path
  tags: 
     - install-app-fp
     - AutoCad-fp
  
- name: AutoCAD FP Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-fp
     - AutoCad-fp

- name: Copy AutoCAD FP UserIntention file to target
  template: src="templates/user_intention_apps/fp/UserIntentions_Autocad_conn_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_Autocad_conn_ga.xml"
  tags: 
     - install-app-fp
     - AutoCad-fp

- name: Copy AutoCAD FP installer from NFS to local
  win_copy:
    src: '{{ apps_FP_installer_path }}\ConnectorforAutoCADServer.Windows64\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-fp
     - AutoCad-fp 
  
- name: Executing AutoCAD installation on target
  win_psexec:
      command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_fp_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_Autocad_conn_ga.xml --xmlreport {{windows_tmp_path}}\Report_AutoCAD_FP.xml'
      elevated: yes
  tags:  
     - install-app-fp
     - AutoCad-fp 

- name: Removing the user Intension file for AutoCAD from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_Autocad_conn_ga.xml" state=absent 
  tags: 
     - install-app-fp
     - AutoCad-fp 
     
- name: Removing the Report for AutoCAD from traget
  win_file: path="{{windows_tmp_path}}\Report_AutoCAD_FP.xml" state=absent
  tags:  
     - install-app-fp
     - AutoCad-fp 
     
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-fp
     - AutoCad-fp 