---

- name: Check if BOM_AVL GA Apps installer path exists
  win_stat: path="{{ apps_GA_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-ga
     - component-exp-ga
  
- name: AutoCAD BOM_AVL GA Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - component-exp-ga

- name: Copy BOM_AVL GA UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_Component_exp_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_Component_exp_ga.xml"
  tags: 
     - install-app-ga
     - component-exp-ga

- name: Copy BOM_AVL GA apps installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\ENOVIAEBOMAVLManagement\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-ga
     - component-exp-ga 
  
- name: Executing BOM_AVL apps installation on target
  win_psexec:
      command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_ga_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_Component_exp_ga.xml --xmlreport {{windows_tmp_path}}\Report_com_exp_GA.xml'
      elevated: yes
  tags: 
     - install-app-ga
     - component-exp-ga

- name: Removing the user Intension file for BOM_AVL from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_Component_exp_ga.xml" state=absent
  tags: 
     - install-app-ga
     - component-exp-ga

- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-ga
     - component-exp-ga