--3.1.2. Commands for 3DSpace
USE [master]
GO
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'$(dbname)') 
	BEGIN
		DROP DATABASE $(dbname);
		PRINT 'DROP DB $(dbname) SUCCESSFUL';
	END
ELSE
	BEGIN
		PRINT '$(dbname) DB NOT EXISTS';
	END
GO
USE master;
-- Create database and assosiated file groups
CREATE DATABASE $(dbname) ON PRIMARY (NAME=$(dbname),
FILENAME= N'$(dbdirectory)\$(dbname).mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [I1_DATA] (NAME=[I1_DATA] ,
FILENAME= N'$(dbdirectory)\I1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [I1_INDEX] (NAME=[I1_INDEX] ,
FILENAME= N'$(dbdirectory)\I1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [M1_DATA] (NAME=[M1_DATA] ,
FILENAME= N'$(dbdirectory)\M1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [M1_INDEX] (NAME=[M1_INDEX] ,
FILENAME= N'$(dbdirectory)\M1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [V1_DATA] (NAME=[V1_DATA] ,
FILENAME= N'$(dbdirectory)\V1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB),
FILEGROUP [V1_INDEX] (NAME=[V1_INDEX] ,
FILENAME= N'$(dbdirectory)\V1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB)
LOG ON (NAME=$(dbname)_log
,FILENAME= N'$(dbdirectory)\$(dbname).ldf',SIZE=100MB)
COLLATE SQL_Latin1_General_CP1_CS_AS;
PRINT 'DB CREATED' 

GO
ALTER DATABASE $(dbname) SET AUTO_CLOSE OFF ;
ALTER DATABASE $(dbname) SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE $(dbname) SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE $(dbname) SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE $(dbname) SET AUTO_UPDATE_STATISTICS_ASYNC ON;
PRINT 'DATABASE ALTERED'
GO
USE master;
GO
-- Create logins
CREATE LOGIN m1 WITH PASSWORD = '$(pasword1)', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
PRINT 'LOG IN CREATED'
GO
USE $(dbname);
GO
CREATE USER m1 FOR LOGIN m1 WITH DEFAULT_SCHEMA =$(schema);
PRINT 'USER m1 CREATED'

-- Create schema
GO
IF (SCHEMA_ID('$(schema)') IS NULL) 
BEGIN
    EXEC ('CREATE SCHEMA $(dbname) AUTHORIZATION [m1]')
END
PRINT 'Schema create successfully..'
-- Grant access
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::$(dbname) TO m1;
PRINT 'Task successful'