---

- name: copy fcs site location bat file to target
  template: src="script_modify_fcs_location.bat.j2" dest="{{windows_tmp_path}}\script_modify_fcs_location.bat"
  tags: 
    - fcs-site-location
    - post-activity#
    
- name: run store config through mql
  win_psexec:
     command: '{{windows_tmp_path}}\script_modify_fcs_location.bat >> {{windows_tmp_path}}\Report_store_config.xml'
     elevated: yes
  tags: 
    - fcs-site-location
    - post-activity#