---


plm_user: "plmd1ma"
plm_group: "plm"
has_plm_volume: no

# Installer Info
mcs_installer_path: "{{ installer_path }}/3dspace"
mcs_ga_installer: "{{ mcs_installer_path }}/ga/platform"
mcs_apps_ga_installer: "{{ mcs_installer_path }}/ga/apps"
mcs_fp_installer: "{{ mcs_installer_path }}/{{ fix_pack_version }}/platform"
mcs_apps_fp_installer: "{{ mcs_installer_path }}/{{ fix_pack_version }}/apps"

code_backup_filename: ""
code_backup_dir: "{{mcs_install_path}}/code_backup"


# Installation dir path
mcs_install_path: "{{ eplm_server_base_path }}/{{ env_name }}"
mcs_install_rel_path: "{{mcs_install_path}}/{{mcs_type}}"
mcs_common_dir: "{{mcs_install_path}}/mcscommon"
mcs_instance_path: "{{mcs_install_rel_path}}/instances"
mcs_code_dir: "{{mcs_install_rel_path}}/code"
mcs_bin_dir: "{{mcs_install_rel_path}}/bin"
mcs_log_dir: "{{mcs_install_rel_path}}/logs"
mcs_orphan_dir: "{{mcs_log_dir}}/dbclean"

mcs_conf_dir: "{{mcs_common_dir}}/conf"
mcs_java_dir: "{{mcs_common_dir}}/softs"
mcs_java_path: "{{mcs_java_dir}}/jdk-mcs"
mcs_server_dir: "{{mcs_code_dir}}/server"
mcs_studio_dir: "{{mcs_install_path}}/studio"
mcs_mya_dir: "{{mcs_code_dir}}/mya"
mcs_evp_dir: "{{mcs_code_dir}}/evp"
mcs_csg_dir: "{{mcs_code_dir}}/csg"
mcs_kwd_dir: "{{mcs_code_dir}}/kwd"
mcs_atk_dir: "{{mcs_code_dir}}/atk"
mcs_dma_dir: "{{mcs_code_dir}}/dma"
build_dir: "{{mcs_server_dir}}/distrib"
mcs_build: "{{ build_dir }}/enovia.war"
java7_version_dir: "{{mcs_java_dir}}/jdk1.7.0_67"
java8_version_dir: "{{mcs_java_dir}}/jdk1.8.0_92"



# Installation infomation
db_option_db2: "2"
db2_product_dir: "/opt/ibm/db2/V10.5"
db2_instance_name: "v6admin"
db2_connection_user: "v6admin"
db2_connection_user_pass: "v6admin"
db2_database_name: "dev1db"
db2_data_tablespace: "MX_DATA"
db2_index_tablespace: "MX_INDEX"
mql_user: "creator"
mql_password: ""
business_data_tbl_spc: "LX_DATA"
business_index_tbl_spc: "LX_INDEX"
app_administrator_user: "admin_platform"
app_administrator_pass: "Jklalrahab321"
storage_data_tablespace: "VPM_DATA"
storage_index_tablespace: "VPM_INDEX"
vpm_repository_name: "My PLM Repository"
vpm_store_path: "{{mcs_evp_dir}}/store/EVP"
product_name: "LIV-MDEVPM"
person_name: "admin_platform"

#DB_clean
user_clean_object: "coexusr1"
password_clean_object: "coexusr1"


# CAS info
mcs_cas_http_url: "http://jkls0326vm45a:8181/"
passport_http_url: "http://jkls0326vm45a:8281/"
mcs_server_url: "https://jkls0326vm45a:8180/"
mcs_callback_url: "https://jkls0326vm45a:8180/enovia/proxyCallback"
cas_server_url: "https://jkls0326vm45a:8280/"
cas_login_url: "https://jkls0326vm45a:8280/3DPassport/login"
cas_targetServiceId: "V6"
mcs_server_enovia_url: "http://i1-mcsnocas-prod-plm.valmet.com:8381/internal"


# FTS info
fts_base_port: "19000"
fts_host: "jkls0326vm45a"
fts_master_host: ""
fts_slave_host: ""
mcs_config_xml: "{{ mcs_server_dir }}/Apps/BusinessProcessServices/V6R2015x/Modules/ENOFramework/AppInstall/Programs/config.xml"

# 3dx info
e3dx_1st_port_range: "58000"
e3dx_start_instance_count: "5"
e3dx_server_name: "jkls0326vm45a"


