---

- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ system_apps_dir }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-fts
    
- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ eplm_server_base_path }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-fts

- name: create symbolic link for /plm
  remote_user: monitor
  become: true
  file: src="{{ eplm_server_base_path }}" dest="/plm" state=link owner=root group=root mode=2777
  when: not has_plm_volume
  tags: 
  - create_dirs
  - install-fts

- name: create the apps env
  remote_user: monitor
  become: true
  file: path="{{ fts_install_path }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs
   - install-fts

- name: create the fts dir
  remote_user: monitor
  become: true
  file: path="{{ fts_install_rel_path }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-fts
   
   
- name: create the code dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ fts_code_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-fts
   
   
- name: create the conf dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ fts_conf_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-fts
  
  
- name: create the soft dir for JDK
  remote_user: monitor
  become: true
  file: path="{{ fts_soft_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  tags: 
    - create_dirs
    - install-fts

- name: create the dir for fts logs
  remote_user: monitor
  become: true
  file: path="{{ fts_log_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=r"
  tags: 
    - create_dirs
    - install-fts
    
- name: create the dir for fts bin
  remote_user: monitor
  become: true
  file: path="{{ fts_bin_path }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=r"
  tags: 
    - create_dirs
    - install-fts

    
- name: change ownership of fts dir
  remote_user: monitor
  become: true
  command: chown -R "{{plm_user}}":"{{plm_group}}" "{{fts_install_rel_path}}" 
  tags: 
   - create_dirs
   - install-fts
