---


- name: Check if java path exists or not
  remote_user: "{{ plm_user }}"
  stat: path="{{fts_jdk_path}}"
  register: check_path
  tags: 
    - install-java
    - install-fts

- name: untar jdk inside instance
  remote_user: monitor
  become: true
  unarchive: src="{{java_installer}}" dest="{{ fts_soft_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  when: not check_path.stat.exists
  tags: 
   - install-java
   - install-fts

- name: get java path
  remote_user: "{{ plm_user }}"
  shell: ls {{ fts_soft_dir }}
  register: dir_content
  when: not check_path.stat.exists
  tags: 
   - install-java
   - install-fts

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ dir_content.stdout }}" dest="{{fts_jdk_path}}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  when: not check_path.stat.exists
  tags: 
   - install-java
   - install-fts
