---

- name: check installation status
  remote_user: monitor
  become: true
  shell: "yum -q list installed {{ item }} | grep -o {{ item }}| head -1"
  register: users_checked
  with_items: "{{ pre_pkgs }}"
  tags:
     - install-prereq
     - install-fts

- name: install
  remote_user: monitor
  become: true
  yum: name={{item.item}} state=present
  with_items: "{{ users_checked.results }}"
  when: item.stdout == ""
  tags:
     - install-prereq
     - install-fts
      
#- name: install pre-requisite packages
#  remote_user: monitor
#  become: true
#  yum: name={{item}} state=present 
#  with_items: pre_pkgs
#  tags:
#     - install-prereq
#     #- install-fts
  
# Check system environment
- name: Check  VM space set unlimited or not
  remote_user: "{{ plm_user }}"
  shell: ulimit -v
  register: vm_stat
  tags: 
    - install-prereq
    - install-fts
    
    
- fail: msg="Failed!! Set VM space to unlimited"
  remote_user: "{{ plm_user }}"
  when: vm_stat.stdout.find('unlimited') == -1
  tags:
     - install-prereq
     - install-fts
     
     
- name: Check  maximum number of file descriptors per process
  remote_user: "{{ plm_user }}"
  shell: ulimit -H -n
  register: mfd_stat
  tags: 
    - install-prereq
    - install-fts
    
    
- fail: msg="Failed!! Increase the number of file descriptors on the server"
  remote_user: "{{ plm_user }}"
  when: mfd_stat.stdout|int < 800000
  tags:
     - install-prereq
     - install-fts
     
     
- name: Check  the number of threads
  remote_user: "{{ plm_user }}" 
  shell: ulimit -H -u
  register: nt_stat
  tags: 
    - install-prereq
    - install-fts
    
    
- fail: msg="Failed!! A minimum of 8K is recommended"
  remote_user: "{{ plm_user }}"
  when: nt_stat.stdout|int < 8192
  tags:
     - install-prereq
     - install-fts


- name: Check  the increase number of threads
  remote_user: "{{ plm_user }}" 
  shell: ulimit -u
  register: nnt_stat
  tags: 
    - install-prereq
    - install-fts
    
    
- fail: msg="Failed!! A minimum increase number of 8K is recommended"
  remote_user: "{{ plm_user }}"
  when: nnt_stat.stdout|int < 8192
  tags:
     - install-prereq
     - install-fts

# Install mesa-libGL
- name: Check mesa-libGL installed or not
  remote_user: monitor
  become: true
  command: rpm -q mesa-libGL
  register: rpm_check1
  ignore_errors: yes
  tags: 
    - install-prereq
    - install-fts
  
- name: copy mesa-libGL to user home Directory
  remote_user: "{{ plm_user }}"
  copy: src="mesa-libGL-10.4.3-1.el6.x86_64.rpm" dest="/tmp/mesa-libGL-10.4.3-1.el6.x86_64.rpm" mode=0755
  when: rpm_check1.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts
    
- name: Install mesa-libGL package.
  remote_user: monitor
  become: true
  yum: 
     name: /tmp/mesa-libGL-10.4.3-1.el6.x86_64.rpm 
     state: present
  when: rpm_check1.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts

# Install mesa-libOSMesa
- name: Check mesa-libOSMesa installed or not
  remote_user: monitor
  become: true
  command: rpm -q mesa-libOSMesa
  register: rpm_check2
  ignore_errors: yes
  tags: 
    - install-prereq
    - install-fts
  
- name: copy mesa-libOSMesa to user home Directory
  remote_user: "{{ plm_user }}"
  copy: src="mesa-libOSMesa-10.4.3-1.el6.x86_64.rpm" dest="/tmp/mesa-libOSMesa-10.4.3-1.el6.x86_64.rpm" mode=0755
  when: rpm_check2.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts
    
- name: Install mesa-libOSMesa package.
  remote_user: monitor
  become: true
  yum: 
     name: /tmp/mesa-libOSMesa-10.4.3-1.el6.x86_64.rpm 
     state: present
  when: rpm_check2.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts
    
# Install xorg-x11-server-Xvfb
- name: Check xorg-x11-server-Xvfb installed or not
  remote_user: monitor
  become: true
  command: rpm -q xorg-x11-server-Xvfb
  register: rpm_check3
  ignore_errors: yes
  tags: 
    - install-prereq
    - install-fts
  
- name: copy xorg-x11-server-Xvfb to user home Directory
  remote_user: "{{ plm_user }}"
  copy: src="xorg-x11-server-Xvfb-1.10.4-6.el6.x86_64.rpm" dest="/tmp/xorg-x11-server-Xvfb-1.10.4-6.el6.x86_64.rpm" mode=0755
  when: rpm_check3.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts
    
- name: Install xorg-x11-server-Xvfb package.
  remote_user: monitor
  become: true
  yum: 
     name: /tmp/xorg-x11-server-Xvfb-1.10.4-6.el6.x86_64.rpm 
     state: present
  when: rpm_check3.stdout.find('is not installed') != -1
  tags: 
    - install-prereq
    - install-fts
    
