---

- name: Stop Advanced Search Server
  remote_user: "{{ plm_user }}"
  shell: ./cvinit.sh stop
  args:
    chdir: /{{ fts_bin_dir }}
  tags: 
    - uninstall-fts



- name: Delete the fts dir
  remote_user: monitor
  become: true
  file: path="{{ fts_install_rel_path }}" state=absent owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: uninstall-fts