---

- name: pre task 
  hosts: 3dpass_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  remote_user: monitor 
  sudo: true
  tags: install-passport
  pre_tasks:
   - name: create dir for mount 
     file: path="{{ mount_dest_dir }}" state=directory
   - name: mounting NFS to local
     mount: name="{{ mount_dest_dir }}" src="{{ mount_src_dir }}" fstype=nfs opts=defaults state=mounted
     tags: mounting

- name: Create user
  hosts: 3dpass_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  tags: install-passport
  remote_user: "monitor"
  sudo: true
  vars:
    plm_user: "plms2pa"
    plm_group: "plm"
  roles:
      - { role: create-user, action: "create" ,  user_name: "{{ plm_user }}", user_pass: "{{ plm_user }}", group_name: "{{ plm_group }}" }

- name: install 3dpassport
  hosts: 3dpass_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
      - 3dpassport/vars/main.yml
      - 3dpassport/vars/{{env_name}}.yml
  remote_user: "{{ plm_user }}"
  sudo: false
  roles:
      - { role: 3dpassport  }	


- name: post tasks
  hosts: 3dpass_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  remote_user: monitor
  sudo: true
  tags: 
    - install-passport-fp
  post_tasks:
    - name: unmounting mounting NFS to local
      mount: name="{{ mount_dest_dir }}" src="{{ mount_src_dir }}" fstype=nfs opts=ro state=unmounted
