---

- name: Pre task 
  hosts: mcs_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  remote_user: monitor 
  sudo: true
  tags: 
    - pre-task
    - make_nfs_mount
  pre_tasks:
   - name: create dir for mount 
     file: path="{{ mount_dest_dir }}" state=directory
   - name: mounting NFS to local
     mount: name="{{ mount_dest_dir }}" src="{{ mount_src_dir }}" fstype=nfs opts=defaults state=mounted
     tags: mounting

- name: Create user
  hosts: mcs_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  tags: pre-task
  remote_user: "monitor"
  sudo: true
  vars:
    plm_user: "plms2ma"
    plm_group: "plm"
  roles:
      - { role: create-user, action: "create" ,  user_name: "{{ plm_user }}", user_pass: "{{ plm_user }}", group_name: "{{ plm_group }}" }


- name: Install mcsnocas
  hosts: mcs_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
      - mcs/vars/main.yml
      - mcs/vars/{{env_name}}.yml
  vars:
    mcs_with_cas: false
    mcs_type: "mcsnocas"
    instance_name: "was_mcsnocas_1"
    instances:
      was_mcsnocas_1:
         app_name: was_mcsnocas_1
         port_http: 8081
         port_jmx: 8099
         port_ajp: 8011
         port_shutdown: 8016
         port_redirect: 8454
  remote_user: "{{plm_user}}"
  sudo: false
  roles:
      - { role: mcs  }	


- name: post tasks
  hosts: mcs_servers
  vars_files:
      - /home/users/as_user/ansible/.sudo_pass
  remote_user: monitor 
  sudo: true
  tasks:
    - name: unmounting NFS from local
      mount: name="{{ mount_dest_dir }}" src="{{ mount_src_dir }}" fstype=nfs opts=ro state=unmounted
  tags: umount-nfs
      
