---
- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ system_apps_dir }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
    
- name: create the base dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ eplm_server_base_path }}" state=directory owner=root group=root mode=2755
  when: not has_plm_volume
  tags: 
   - create_dirs
   - install-mcs
   - pre-task 

- name: create symbolic link
  remote_user: monitor
  become: true
  file: src="{{ eplm_server_base_path }}" dest="/plm" state=link owner=root group=root mode=2777
  when: not has_plm_volume
  tags: 
  - create_dirs
  - install-mcs
  - pre-task

- name: create the apps env
  remote_user: monitor
  become: true
  file: path="{{ mcs_install_path }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task

- name: create the mcs dir
  remote_user: monitor
  become: true
  file: path="{{ mcs_install_rel_path }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
   
- name: create the mcscommon dir
  remote_user: monitor
  become: true
  file: path="{{ mcs_common_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
   
- name: create the code dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_code_dir }}" state=directory owner=root group=root mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
   
- name: create the bin dir
  remote_user: monitor
  become: true
  file: path="{{ mcs_bin_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
   
- name: create the conf dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2755
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
  
- name: create the tomcat instance dir
  remote_user: monitor
  become: true
  file: path="{{ mcs_instance_path }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  tags: 
    - create_dirs
    - install-mcs
    - pre-task
    
- name: create the soft dir for JDK
  remote_user: monitor
  become: true
  file: path="{{ mcs_java_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  tags: 
    - create_dirs
    - install-mcs
    - pre-task

- name: create the dir for mcs logs
  remote_user: monitor
  become: true
  file: path="{{ mcs_log_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=r"
  tags: 
    - create_dirs
    - install-mcs
    - pre-task

- name: create the dir for logs
  remote_user: monitor
  become: true
  file: path="{{ mcs_log_dir }}/{{ item }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  with_items: 
   - code
   - elt
  tags: 
    - create_dirs
    - install-mcs
    - pre-task

- name: create the dir for instance logs
  remote_user: monitor
  become: true
  file: path="{{ mcs_log_dir }}/{{ item.key }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=r"
  with_dict: "{{ instances }}"
  tags: 
    - create_dirs
    - install-mcs
    - pre-task
    
- name: change ownership in mcs dir
  remote_user: monitor
  become: true
  command: chown -R "{{plm_user}}":"{{plm_group}}" "{{mcs_install_rel_path}}" 
  tags: 
   - create_dirs
   - install-mcs
   - pre-task
