---

- name: copy KOALA.properties in conf
  template: src="KOALA.properties.j2" dest="{{ mcs_conf_dir }}/KOALA.properties" 
  tags: 
    - koala-config
    - post-activity
    
- name: copy KOALAEnv.properties in conf
  template: src="KOALAEnv.properties.j2" dest="{{ mcs_server_dir }}/managed/properties/KOALAEnv.properties" 
  tags: 
    - koala-config
    - post-activity
    
- name: copy KOALA.properties in conf
  template: src="KOALA.properties.j2" dest="{{ mcs_server_dir }}/managed/properties/KOALA.properties" 
  tags: 
    - koala-config
    - post-activity
    
    
- name: copy KOALAEnv.properties in conf
  template: src="KOALAEnv.properties.j2" dest="{{ mcs_server_dir }}/STAGING/ematrix/WEB-INF/classes/KOALAEnv.properties" 
  tags: 
    - koala-config
    - post-activity