---
  
    
- name: Copy fcs_store_configaration.sh in mcs bin dir
  template: src="script.modify.fcs.store.j2" dest="{{ mcs_bin_dir }}/modify_fcs_stores.sh" mode=0755
  tags: update-fcs-store
     
- name: Execute the modify_fcs_stores.sh script
  shell: ./modify_fcs_stores.sh > modify_fcs_stores.log 2>&1
  args:
    chdir: /{{ mcs_bin_dir }}
  tags: update-fcs-store
  
  
- name: Copy fcs_store_configaration.sh in mcs bin dir
  template: src="script.modify.fcs.location.j2" dest="{{ mcs_bin_dir }}/modify_fcs_site_locations.sh" mode=0755
  tags: update-fcs-site-location
     
- name: Execute the modify_fcs_site_locations.sh script
  shell: ./modify_fcs_site_locations.sh > modify_fcs_site_locations.log 2>&1
  args:
    chdir: /{{ mcs_bin_dir }}
  tags: update-fcs-site-location
  
  


    