---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes 
  tags: 
     - ENOVIAVariantConfiguration-FP
     
     
- name: Copy the Variant Configuration Central fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_variantconf_centralfx.j2" dest="{{ mcs_conf_dir }}/answer_variantconf_centralfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAVariantConfiguration-FP
     - install-mcsfx
     - install-apps-fp
   
- name: Copy the Variant Configuration Central fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_variantconf_centralfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_variantconf_centralfx.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAVariantConfiguration-FP
     - install-mcsfx
     - install-apps-fp

- name: Executing the Variant Configuration Central fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_variantconf_centralfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ENOVIAVariantConfigurationCentral.Unix64/1
  tags: 
     - ENOVIAVariantConfiguration-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Variant Configuration Central fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_variantconf_centralfx.txt" state=absent
  tags: 
     - ENOVIAVariantConfiguration-FP
     - install-mcsfx
     - install-apps-fp
     
