---
 
- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ConnectorforSolidWorksServer
  
  
- name: Copy the Connector for SolidWorks Server Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_conn_solidworks.j2" dest="{{ mcs_conf_dir }}/answer_conn_solidworks.txt" mode=2777
  tags: 
    - ConnectorforSolidWorksServer
    - install-mcs
    - install-apps-ga

- name: Executing the Connector for SolidWorks Server installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_conn_solidworks.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ConnectorforSolidWorksServer.Unix64/1
  tags: 
      - ConnectorforSolidWorksServer
      - install-mcs
      - install-apps-ga
   

- name: Remove the Connector for SolidWorks Server Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_conn_solidworks.txt" state=absent
  tags: 
     - ConnectorforSolidWorksServer
     - install-mcs
     - install-apps-ga


