---

- name: create symbolic link for java 8
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIABusinessProcessServices-FP
    

- name: Copy Business Process Service Fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_business_processfx.j2" dest="{{ mcs_conf_dir }}/answer_business_process.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIABusinessProcessServices-FP
    - install-mcsfx
  
  
- name: Copy Business Process Service Fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_business_processfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_business_process.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIABusinessProcessServices-FP
    - install-mcsfx


- name: Executing the Business Process Service Fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_business_process.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIABusinessProcessServices.Unix64/1
  tags: 
    - ENOVIABusinessProcessServices-FP
    - install-mcsfx
   
   
- name: Remove the Business Process Service Fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_business_process.txt" state=absent
  tags: 
     - ENOVIABusinessProcessServices-FP
     - install-mcsfx