---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAVariantConfiguration
  
  
- name: Copy the Variant Configuration Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_variantconf_central.j2" dest="{{ mcs_conf_dir }}/answer_variantconf_central.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAVariantConfiguration
    - install-mcs
    - install-apps-ga
   
   
- name: Copy the Variant Configuration Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_variantconf_central_nudb.j2" dest="{{ mcs_conf_dir }}/answer_variantconf_central.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAVariantConfiguration
     - install-mcs
     - install-apps-ga
   

- name: Executing the Variant Configuration Central installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_variantconf_central.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAVariantConfigurationCentral.Unix64/1
  tags: 
     - ENOVIAVariantConfiguration
     - install-mcs
     - install-apps-ga
   

- name: Remove the Variant Configuration Central Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_variantconf_central.txt" state=absent
  tags: 
    - ENOVIAVariantConfiguration
    - install-mcs
    - install-apps-ga
    