---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment-FP
     

- name: Copy the BOM Configured Environment fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_conf_envfx.j2" dest="{{ mcs_conf_dir }}/answer_bom_conf_envfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the BOM Configured Environment fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_conf_env_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_bom_conf_envfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIAX-BOMConfiguredEnvironment-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the BOM Configured Environment fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_bom_conf_envfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the BOM Configured Environment fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_bom_conf_envfx.txt" state=absent
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment-FP
     - install-mcsfx
     - install-apps-fp

