---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIAStudioFederationToolkit-FP

     
- name: Copy the Studio Federation Toolkit fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_studio_toolkitfx.j2" dest="{{ mcs_conf_dir }}/answer_studio_toolkitfx.txt" mode=2777
  tags: 
    - ENOVIAStudioFederationToolkit-FP
    - install-apps-fp

- name: Executing the Studio Federation Toolkit fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_studio_toolkitfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ENOVIAStudioFederationToolkit.Linux64/1
  tags: 
     - ENOVIAStudioFederationToolkit-FP
     - install-apps-fp
   

- name: Remove the Studio Federation Toolkit fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_studio_toolkitfx.txt" state=absent
  tags: 
     - ENOVIAStudioFederationToolkit-FP
     - install-apps-fp

