---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
     - ENOVIAKnowledgeStandardization
  
- name: create the kwd dir for Knowledge Standardization or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_kwd_dir }}" state=directory owner={{plm_user}} group={{plm_group}} mode=2755
  tags: 
     - ENOVIAKnowledgeStandardization
     - install-mcs
     - install-apps-ga
   
- name: Copy the Knowledge Standardization Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_know_std.j2" dest="{{ mcs_conf_dir }}/answer_know_std.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAKnowledgeStandardization
     - install-mcs
     - install-apps-ga
   
   
- name: Copy the Knowledge Standardization Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_know_std_nudb.j2" dest="{{ mcs_conf_dir }}/answer_know_std.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAKnowledgeStandardization
     - install-mcs
     - install-apps-ga

- name: Executing the Knowledge Standardization installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_know_std.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAKnowledgeStandardization.Unix64/1
  tags: 
     - ENOVIAKnowledgeStandardization
     - install-mcs
     - install-apps-ga
   
   
- name: Remove the Knowledge Standardization Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_know_std.txt" state=absent
  tags: 
     - ENOVIAKnowledgeStandardization
     - install-mcs
     - install-apps-ga



