---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAKnowledgeStandardization-FP

          
- name: Copy the Knowledge Standardization fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_know_stdfx.j2" dest="{{ mcs_conf_dir }}/answer_know_stdfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAKnowledgeStandardization-FP
     - install-mcsfx
     - install-apps-fp

- name: Copy the Knowledge Standardization fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_know_stdfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_know_stdfx.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAKnowledgeStandardization-FP
     - install-mcsfx
     - install-apps-fp

- name: Executing the Knowledge Standardization fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_know_stdfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ENOVIAKnowledgeStandardization.Unix64/1
  tags: 
     - ENOVIAKnowledgeStandardization-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Knowledge Standardization fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_know_stdfx.txt" state=absent
  tags: 
     - ENOVIAKnowledgeStandardization-FP
     - install-mcsfx
     - install-apps-fp



