---
 
- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
     - ENOVIAProgramChangeControl
  
- name: Copy the Program Change Control Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_change_control.j2" dest="{{ mcs_conf_dir }}/answer_prog_change_control.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAProgramChangeControl
    - install-mcs
    - install-apps-ga
   
- name: Copy the Program Change Control Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_change_control_nudb.j2" dest="{{ mcs_conf_dir }}/answer_prog_change_control.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAProgramChangeControl
     - install-mcs
     - install-apps-ga

- name: Executing the Program Change Control installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_prog_change_control.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAProgramChangeControl.Unix64/1
  tags: 
     - ENOVIAProgramChangeControl
     - install-mcs
     - install-apps-ga
   

- name: Remove the Program Change Control Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_prog_change_control.txt" state=absent
  tags: 
     - ENOVIAProgramChangeControl
     - install-mcs
     - install-apps-ga

