---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAMicrosoftProjectIntegrationServer
  
- name: Copy the Microsoft Project Integration Server Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_micro_proj_intrsrv.j2" dest="{{ mcs_conf_dir }}/answer_micro_proj_intrsrv.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAMicrosoftProjectIntegrationServer
    - install-mcs
    - install-apps-ga
   
- name: Copy the Microsoft Project Integration Server Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_micro_proj_intrsrv_nudb.j2" dest="{{ mcs_conf_dir }}/answer_micro_proj_intrsrv.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer
     - install-mcs
     - install-apps-ga

- name: Executing the Microsoft Project Integration Server installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_micro_proj_intrsrv.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer
     - install-mcs
     - install-apps-ga
   

- name: Remove the Microsoft Project Integration Server Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_micro_proj_intrsrv.txt" state=absent
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer
     - install-mcs
     - install-apps-ga

