---
 
- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAProgramExperience
  
- name: Copy the Program Experience Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_experience.j2" dest="{{ mcs_conf_dir }}/answer_prog_experience.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAProgramExperience
    - install-mcs
    - install-apps-ga
   
- name: Copy the Program Experience Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_experience_nudb.j2" dest="{{ mcs_conf_dir }}/answer_prog_experience.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAProgramExperience
     - install-mcs
     - install-apps-ga

- name: Executing the Program Experience installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_prog_experience.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAProgramExperience.Unix64/1
  tags: 
     - ENOVIAProgramExperience
     - install-mcs
     - install-apps-ga
   

- name: Remove the Program Experience Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_prog_experience.txt" state=absent
  tags: 
     - ENOVIAProgramExperience
     - install-mcs
     - install-apps-ga

