---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIACollaborativeSpaceManagement-FP
     
   
- name: Copy the Collaborative Space Management fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_collspace_mgtfx.j2" dest="{{ mcs_conf_dir }}/answer_collspace_mgtfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIACollaborativeSpaceManagement-FP
     - install-mcsfx
  
  
- name: Copy the Collaborative Space Management fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_collspace_mgtfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_collspace_mgtfx.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIACollaborativeSpaceManagement-FP
     - install-mcsfx


- name: Executing the Collaborative Space Management fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_collspace_mgtfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIACollaborativeSpaceManagement.Unix64/1
  tags: 
     - ENOVIACollaborativeSpaceManagement-FP
     - install-mcsfx
   

- name: Remove the Collaborative Space Management fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_collspace_mgtfx.txt" state=absent
  tags: 
     - ENOVIACollaborativeSpaceManagement-FP
     - install-mcsfx
   
   
   
