---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIACompliansandNCRFoundation-FP


- name: Copy the Complians And NCR Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_comp_ncr_foundationfx.j2" dest="{{ mcs_conf_dir }}/answer_comp_ncr_foundationfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIACompliansandNCRFoundation-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the Complians And NCR Foundationfixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_comp_ncr_foundation_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_comp_ncr_foundationfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIACompliansandNCRFoundation-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Complians And NCR Foundation fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_comp_ncr_foundationfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAComplaintsandNCRFoundation.Unix64/1
  tags: 
     - ENOVIACompliansandNCRFoundation-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Complians And NCR Foundation fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_comp_ncr_foundationfx.txt" state=absent
  tags: 
     - ENOVIACompliansandNCRFoundation-FP
     - install-mcsfx
     - install-apps-fp

