---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIACollaborationforMicrosoftServer-FP


- name: Copy the Collaboration for Microsoft Serverfixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_coll_microsoft_serverfx.j2" dest="{{ mcs_conf_dir }}/answer_coll_microsoft_serverfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIACollaborationforMicrosoftServer-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the Collaboration for Microsoft Server fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_coll_microsoft_server_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_coll_microsoft_serverfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIACollaborationforMicrosoftServer-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Collaboration for Microsoft Server fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_coll_microsoft_serverfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1
  tags: 
     - ENOVIACollaborationforMicrosoftServer-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Collaboration for Microsoft Server fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_coll_microsoft_serverfx.txt" state=absent
  tags: 
     - ENOVIACollaborationforMicrosoftServer-FP
     - install-mcsfx
     - install-apps-fp

