---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAX-CADDesignFoundation-FP

   
- name: Copy the CAD Design Foundation fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_caddes_foundationfx.j2" dest="{{ mcs_conf_dir }}/answer_caddes_foundationfx.txt" mode=2777
  tags: 
     - ENOVIAX-CADDesignFoundation-FP
     - install-mcsfx
     - install-apps-fp

- name: Executing the CAD Design Foundation fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_caddes_foundationfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ENOVIAX-CADDesignFoundation.Unix64/1
  tags: 
     - ENOVIAX-CADDesignFoundation-FP
     - install-mcsfx
     - install-apps-fp

- name: Remove the CAD Design Foundation fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_caddes_foundationfx.txt" state=absent
  tags:  
     - ENOVIAX-CADDesignFoundation-FP
     - install-mcsfx
     - install-apps-fp