---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIACollaborationforMicrosoftServer
  
  
- name: Copy the Collaboration for Microsoft Server Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_coll_microsoft_server.j2" dest="{{ mcs_conf_dir }}/answer_coll_microsoft_server.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIACollaborationforMicrosoftServer
    - install-mcs
    - install-apps-ga
   
- name: Copy the Collaboration for Microsoft Server Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_coll_microsoft_server_nudb.j2" dest="{{ mcs_conf_dir }}/answer_coll_microsoft_server.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIACollaborationforMicrosoftServer
     - install-mcs
     - install-apps-ga

- name: Executing the Collaboration for Microsoft Server installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_coll_microsoft_server.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIACollaborationforMicrosoftServer.Unix64/1
  tags: 
     - ENOVIACollaborationforMicrosoftServer
     - install-mcs
     - install-apps-ga
   

- name: Remove the Collaboration for Microsoft Server Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_coll_microsoft_server.txt" state=absent
  tags: 
     - ENOVIACollaborationforMicrosoftServer
     - install-mcs
     - install-apps-ga

