---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAIntegrationExchangeFramework-FP


- name: Copy the Integration Exchange Framework fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_intex_frameworkfx.j2" dest="{{ mcs_conf_dir }}/answer_intex_frameworkfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAIntegrationExchangeFramework-FP
     - install-mcsfx
     - install-apps-fp

- name: Copy the Integration Exchange Framework fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_intex_framework_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_intex_frameworkfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIAIntegrationExchangeFramework-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Integration Exchange Framework fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_intex_frameworkfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAIntegrationExchangeFramework.Unix64/1
  tags: 
     - ENOVIAIntegrationExchangeFramework-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Integration Exchange Framework fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_intex_frameworkfx.txt" state=absent
  tags: 
     - ENOVIAIntegrationExchangeFramework-FP
     - install-mcsfx
     - install-apps-fp

