---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIALibraryCentral-FP


- name: Copy the Library Central fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_lib_centralfx.j2" dest="{{ mcs_conf_dir }}/answer_lib_centralfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIALibraryCentral-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the Library Central fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_lib_central_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_lib_centralfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIALibraryCentral-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Library Central fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_lib_centralfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIALibraryCentral.Unix64/1
  tags: 
     - ENOVIALibraryCentral-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Library Central fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_lib_centralfx.txt" state=absent
  tags: 
     - ENOVIALibraryCentral-FP
     - install-mcsfx
     - install-apps-fp

