---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIACollaborativeSpaceManagement
  
  
- name: create the csg dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_csg_dir }}" state=directory owner={{plm_user}} group={{plm_group}} mode=2755
  tags: 
     - ENOVIACollaborativeSpaceManagement
     - install-mcs
 
 
- name: Copy the Collaborative Space Management Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_collspace_mgt.j2" dest="{{ mcs_conf_dir }}/answer_collspace_mgt.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIACollaborativeSpaceManagement
    - install-mcs
   
   
- name: Copy the Collaborative Space Management Answer file (database will not update)
  remote_user: monitor
  become: true
  template: src="answer_collspace_mgt_nudb.j2" dest="{{ mcs_conf_dir }}/answer_collspace_mgt.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIACollaborativeSpaceManagement
     - install-mcs


- name: Executing the Collaborative Space Management installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_collspace_mgt.txt
  args:
    chdir: /{{ mcs_ga_installer }}/ENOVIACollaborativeSpaceManagement.Unix64/1
  tags: 
    - ENOVIACollaborativeSpaceManagement
    - install-mcs
   

- name: Remove the Collaborative Space Management Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_collspace_mgt.txt" state=absent
  tags: 
     - ENOVIACollaborativeSpaceManagement
     - install-mcs
     