---
 
- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIAX-BOMConfiguredEnvironment
  
  
- name: Copy the BOM Configured Environment Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_conf_env.j2" dest="{{ mcs_conf_dir }}/answer_bom_conf_env.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAX-BOMConfiguredEnvironment
    - install-mcs
    - install-apps-ga
   
- name: Copy the BOM Configured Environment Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_conf_env_nudb.j2" dest="{{ mcs_conf_dir }}/answer_bom_conf_env.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment
     - install-mcs
     - install-apps-ga

- name: Executing the BOM Configured Environment installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_bom_conf_env.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAX-BOMConfiguredEnvironment.Unix64/1
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment
     - install-mcs
     - install-apps-ga
   

- name: Remove the BOM Configured Environment Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_bom_conf_env.txt" state=absent
  tags: 
     - ENOVIAX-BOMConfiguredEnvironment
     - install-mcs
     - install-apps-ga

