---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAEnterpriseAVLManagement
  
- name: Copy the Enterprise AVL Management Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_ent_avl_mgt.j2" dest="{{ mcs_conf_dir }}/answer_ent_avl_mgt.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAEnterpriseAVLManagement
    - install-apps-ga

   
- name: Copy the Enterprise AVL Management Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_ent_avl_mgt_nudb.j2" dest="{{ mcs_conf_dir }}/answer_ent_avl_mgt.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAEnterpriseAVLManagement
     - install-apps-ga


- name: Executing the Enterprise AVL Management installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_ent_avl_mgt.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAEnterpriseAVLManagement.Unix64/1
  tags: 
     - ENOVIAEnterpriseAVLManagement
     - install-apps-ga

   

- name: Remove the Enterprise AVL Management Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_ent_avl_mgt.txt" state=absent
  tags: 
     - ENOVIAEnterpriseAVLManagement
     - install-apps-ga
