---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIALiveCollaborationServer-FP


- name: Copy the Live Collaboration Server Fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_serverfx.j2" dest="{{ mcs_conf_dir }}/answer_serverfx.txt" mode=2777
  tags: 
   - install-mcsfx
   - ENOVIALiveCollaborationServer-FP

- name: Executing the Live Collaboration Server Fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh < {{ mcs_conf_dir }}/answer_serverfx.txt
  args:
    chdir: /{{ mcs_fp_installer }}/ENOVIALiveCollaborationServer.Linux64/1
  tags: 
   - install-mcsfx
   - ENOVIALiveCollaborationServer-FP
   

- name: Remove the Live Collaboration Server Fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_serverfx.txt" state=absent
  tags: 
   - install-mcsfx
   - ENOVIALiveCollaborationServer-FP