---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform-FP

     
- name: Copy the Multi Discipline fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_multidis_collplatfx.j2" dest="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform-FP
     - install-mcsfx
  
- name: Copy the Multi Discipline fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_multidis_collplatfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform-FP
     - install-mcsfx

- name: Executing the Multi Discipline fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_multidis_collplat.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform-FP
     - install-mcsfx


- name: Remove the Multi Discipline fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" state=absent
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform-FP
     - install-mcsfx