---

- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
   - 3DEXPERIENCEAppsManagement
  
  
- name: create the mya dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_mya_dir }}" state=directory owner={{plm_user}} group={{plm_group}} mode=2755
  tags: 
   - install-mcs
   - 3DEXPERIENCEAppsManagement
   
- name: copy answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_3dexapps.j2" dest="{{ mcs_conf_dir }}/answer_3dexapps.txt" mode=2777
  when: update_database
  tags: 
   - install-mcs
   - 3DEXPERIENCEAppsManagement
   
- name: copy answer file (database will not update)
  remote_user: monitor
  become: true
  template: src="answer_3dexapps_nudb.j2" dest="{{ mcs_conf_dir }}/answer_3dexapps.txt" mode=2777
  when: not update_database
  tags: 
   - install-mcs
   - 3DEXPERIENCEAppsManagement

- name: Executing the installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_3dexapps.txt
  args:
    chdir: /{{ mcs_ga_installer }}/3DEXPERIENCEAppsManagement.Unix64/1
  tags: 
   - install-mcs
   - 3DEXPERIENCEAppsManagement

- name: remove the answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_3dexapps.txt" state=absent
  tags: 
   - install-mcs
   - 3DEXPERIENCEAppsManagement