---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAMultiDisciplineCollaborationPlatform
  
- name: create the mya dir or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_evp_dir }}" state=directory owner={{plm_user}} group={{plm_group}} mode=2755
  tags: 
    - ENOVIAMultiDisciplineCollaborationPlatform
    - install-mcs

 
- name: Copy the Multi Discipline Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_multidis_collplat.j2" dest="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform
     - install-mcs

   
- name: Copy the Multi Discipline  Answer file (database will not update)
  remote_user: monitor
  become: true
  template: src="answer_multidis_collplat_nudb.j2" dest="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform
     - install-mcs


- name: Executing the Multi Discipline installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_multidis_collplat.txt
  args:
    chdir: /{{ mcs_ga_installer }}/ENOVIAMultiDisciplineCollaborationPlatform.Unix64/1
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform
     - install-mcs
  

- name: Remove the Multi Discipline Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_multidis_collplat.txt" state=absent
  tags: 
     - ENOVIAMultiDisciplineCollaborationPlatform
     - install-mcs