---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIAX-CADDesignFoundation
  
  
- name: Copy the CAD Design Foundation Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_caddes_foundation.j2" dest="{{ mcs_conf_dir }}/answer_caddes_foundation.txt" mode=2777
  tags: 
    - ENOVIAX-CADDesignFoundation
    - install-mcs
    - install-apps-ga

- name: Executing the CAD Design Foundation installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_caddes_foundation.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAX-CADDesignFoundation.Unix64/1
  tags: 
     - ENOVIAX-CADDesignFoundation
     - install-mcs
     - install-apps-ga
   

- name: Remove the CAD Design Foundation Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_caddes_foundation.txt" state=absent
  tags: 
    - ENOVIAX-CADDesignFoundation
    - install-mcs
    - install-apps-ga


