---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAProgramChangeControl-FP


- name: Copy the Program Change Control fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_change_controlfx.j2" dest="{{ mcs_conf_dir }}/answer_prog_change_controlfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAProgramChangeControl-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the Program Change Control fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_prog_change_control_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_prog_change_controlfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIAProgramChangeControl-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Program Change Control fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_prog_change_controlfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAProgramChangeControl.Unix64/1
  tags: 
     - ENOVIAProgramChangeControl-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Program Change Control fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_prog_change_controlfx.txt" state=absent
  tags: 
     - ENOVIAProgramChangeControl-FP
     - install-mcsfx
     - install-apps-fp

