---
- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - 3DEXPERIENCEAppsManagement-FP

  
- name: Copy the 3DExperience Apps Management Fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_3dexappsfx.j2" dest="{{ mcs_conf_dir }}/answer_3dexappsfx.txt" mode=2777
  when: update_database
  tags: 
    - 3DEXPERIENCEAppsManagement-FP
    - install-mcsfx
  
- name: Copy the 3DExperience Apps Management Fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_3dexappsfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_3dexappsfx.txt" mode=2777
  when: not update_database
  tags: 
    - 3DEXPERIENCEAppsManagement-FP
    - install-mcsfx

- name: Executing the 3DExperience Apps Management Fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_3dexappsfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/platform/3DEXPERIENCEAppsManagement.Unix64/1
  tags: 
     - 3DEXPERIENCEAppsManagement-FP
     - install-mcsfx
   

- name: Remove the 3DExperience Apps Management Fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_3dexappsfx.txt" state=absent
  tags: 
     - 3DEXPERIENCEAppsManagement-FP
     - install-mcsfx
