---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAEBOMAVLManagement-FP


- name: Copy the EBOMAVL Management fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_avl_mgtfx.j2" dest="{{ mcs_conf_dir }}/answer_bom_avl_mgtfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAEBOMAVLManagement-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the EBOMAVL Management fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_avl_mgt_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_bom_avl_mgtfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIAEBOMAVLManagement-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the EBOMAVL Management fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_bom_avl_mgtfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAEBOMAVLManagement.Unix64/1
  tags: 
     - ENOVIAEBOMAVLManagement-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the EBOMAVL Management fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_bom_avl_mgtfx.txt" state=absent
  tags: 
     - ENOVIAEBOMAVLManagement-FP
     - install-mcsfx
     - install-apps-fp

