---

    
- name: Check if Life-Science-FP NFS installer path exists
  stat: path="{{ mcs_apps_fp_installer }}/ENOVIALifeSciencesAcceleratorforProductIntroduction.Unix64"
  register: check_path
  tags:
    - ENOVIALIFESCIENCESManagement-FP
    
- name: Installer doesn't exist in NFS
  fail: msg="Life-Science-FP installer doesn't exist!!"
  when: not check_path.stat.exists
  tags:
    - ENOVIALIFESCIENCESManagement-FP

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIALIFESCIENCESManagement-FP

      
- name: Copy the Life Sciences New Product fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_life_sciences_productfix.j2" dest="{{ mcs_conf_dir }}/answer_life_sciences_productfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIALIFESCIENCESManagement-FP
     - install-mcsfx
     - install-apps-fp

- name: Copy the Life Sciences New Product fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_life_sciences_productfx_nudb.j2" dest="{{ mcs_conf_dir }}/answer_life_sciences_productfx.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIALIFESCIENCESManagement-FP
     - install-mcsfx
     - install-apps-fp

- name: Executing the Life Sciences New Product fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_life_sciences_productfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIALifeSciencesAcceleratorforProductIntroduction.Unix64/1
  tags: 
     - ENOVIALIFESCIENCESManagement-FP
     - install-mcsfx
     - install-apps-fp
   
   
- name: Remove the Life Sciences New Product fixpack answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_life_sciences_productfx.txt" state=absent
  tags: 
     - ENOVIALIFESCIENCESManagement-FP
     - install-mcsfx
     - install-apps-fp
