---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAEngineeringCentral
  
- name: Copy the Engineering Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_eng_central.j2" dest="{{ mcs_conf_dir }}/answer_eng_central.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAEngineeringCentral
    - install-mcs
    - install-apps-ga
   
- name: Copy the Engineering Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_eng_central_nudb.j2" dest="{{ mcs_conf_dir }}/answer_eng_central.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAEngineeringCentral
     - install-mcs
     - install-apps-ga

- name: Executing the Engineering Central installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_eng_central.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAEngineeringCentral.Unix64/1
  tags: 
     - ENOVIAEngineeringCentral
     - install-mcs
     - install-apps-ga
   

- name: Remove the Engineering Central answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_eng_central.txt" state=absent
  tags: 
     - ENOVIAEngineeringCentral
     - install-mcs
     - install-apps-ga
