---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    -  ENOVIALibraryCentral
   
- name: Copy the Library Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_lib_central.j2" dest="{{ mcs_conf_dir }}/answer_lib_central.txt" mode=2777
  when: update_database
  tags: 
    -  ENOVIALibraryCentral
    - install-mcs
    - install-apps-ga
   
- name: Copy the Library Central Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_lib_central_nudb.j2" dest="{{ mcs_conf_dir }}/answer_lib_central.txt" mode=2777
  when: not update_database
  tags: 
     -  ENOVIALibraryCentral
     - install-mcs
     - install-apps-ga

- name: Executing the Library Central installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_lib_central.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIALibraryCentral.Unix64/1
  tags: 
     -  ENOVIALibraryCentral
     - install-mcs
     - install-apps-ga
   

- name: Remove the Library Central answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_lib_central.txt" state=absent
  tags: 
     -  ENOVIALibraryCentral
     - install-mcs
     - install-apps-ga
