---
 
- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIAStudioFederationToolkit
  
  
- name: Create the atk dir for Studio Federation Toolkit or make sure it exist
  remote_user: monitor
  become: true
  file: path="{{ mcs_atk_dir }}" state=directory owner={{plm_user}} group={{plm_group}} mode=2755
  tags: 
     - ENOVIAStudioFederationToolkit
     - install-mcs
     - install-apps-ga
    
- name: Copy the Studio Federation Toolkit Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_studio_toolkit.j2" dest="{{ mcs_conf_dir }}/answer_studio_toolkit.txt" mode=2777
  tags: 
     - ENOVIAStudioFederationToolkit
     - install-mcs
     - install-apps-ga

- name: Executing the Studio Federation Toolkit installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_studio_toolkit.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAStudioFederationToolkit.Linux64/1
  tags: 
     - ENOVIAStudioFederationToolkit
     - install-mcs
     - install-apps-ga
   

- name: Remove the Studio Federation Toolkit Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_studio_toolkit.txt" state=absent
  tags: 
     - ENOVIAStudioFederationToolkit
     - install-mcs
     - install-apps-ga
