---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer-FP


- name: Copy the Microsoft Project Integration Server fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_micro_proj_intrsrvfx.j2" dest="{{ mcs_conf_dir }}/answer_micro_proj_intrsrvfx.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer-FP
     - install-mcsfx
     - install-apps-fp


- name: Copy the Microsoft Project Integration Server fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_micro_proj_intrsrv_nudbfx.j2" dest="{{ mcs_conf_dir }}/answer_micro_proj_intrsrvfx.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIAMicrosoftProjectIntegrationServer-FP
    - install-mcsfx
    - install-apps-fp


- name: Executing the Microsoft Project Integration Server fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_micro_proj_intrsrvfx.txt
  args:
    chdir: /{{ mcs_apps_fp_installer }}/ENOVIAMicrosoftProjectIntegrationServer.Unix64/1
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Microsoft Project Integration Server fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_micro_proj_intrsrvfx.txt" state=absent
  tags: 
     - ENOVIAMicrosoftProjectIntegrationServer-FP
     - install-mcsfx
     - install-apps-fp

