---

- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java8_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ConnectorforAutoCADServer-FP

     
- name: Copy the Connector for AutoCAD Server fixpack Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_conn_autocadfx.j2" dest="{{ mcs_conf_dir }}/answer_conn_autocadfx.txt" mode=2777
  tags: 
     - ConnectorforAutoCADServer-FP
     - install-mcsfx
     - install-apps-fp

- name: Executing the Connector for AutoCAD Server fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_fp_installer_path }} < {{ mcs_conf_dir }}/answer_conn_autocadfx.txt
  args:
    chdir: /{{ mcs_installer_path }}/{{ fix_pack_version }}/apps/ConnectorforAutoCADServer.Unix64/1
  register: cat
  tags: 
     - ConnectorforAutoCADServer-FP
     - install-mcsfx
     - install-apps-fp
   

- name: Remove the Connector for AutoCAD Server fixpack Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_conn_autocadfx.txt" state=absent
  tags: 
     - ConnectorforAutoCADServer-FP
     - install-mcsfx
     - install-apps-fp
