---



- name: untar jdk 7 inside softs
  remote_user: monitor
  become: true
  unarchive: src="{{java_installer}}" dest="{{ mcs_java_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  tags: 
     - install-java
     - pre-task

- name: untar jdk 8 inside softs
  remote_user: monitor
  become: true
  unarchive: src="{{java8_installer}}" dest="{{ mcs_java_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  tags: 
     - install-java
     - pre-task

   
- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - install-java
    - pre-task
