---
 
- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIA3DLiveExamine
  
  
- name: Copy the 3DLiveExamine Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_3dlive.j2" dest="{{ mcs_conf_dir }}/answer_3dlive.txt" mode=2777
  tags: 
     - ENOVIA3DLiveExamine
     - install-mcs
     - install-apps-ga

- name: Executing the 3DLiveExamine installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_3dlive.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIA3DLiveExamine.AllOS/1
  tags: 
     - ENOVIA3DLiveExamine
     - install-mcs
     - install-apps-ga
   

- name: Remove the 3DLiveExamine Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_3dlive.txt" state=absent
  tags: 
     - ENOVIA3DLiveExamine
     - install-mcs
     - install-apps-ga

