---
    
- name: Check if Life-Science NFS installer path exists
  stat: path="{{ mcs_apps_ga_installer }}/ENOVIALifeSciencesAcceleratorforProductIntroduction.Unix64"
  register: check_path
  tags:
    - ENOVIALIFESCIENCESManagement
    
- name: Installer doesn't exist in NFS
  fail: msg="Life-Science installer doesn't exist!!"
  when: not check_path.stat.exists
  tags:
    - ENOVIALIFESCIENCESManagement


- name: create symbolic link for the java path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
     - ENOVIALIFESCIENCESManagement


- name: Copy the Life Sciences New Product Management ga Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_life_sciences_product.j2" dest="{{ mcs_conf_dir }}/answer_life_sciences_product.txt" mode=2777
  when: update_database
  tags: 
     - ENOVIALIFESCIENCESManagement
     - install-apps-ga


- name: Copy the Life Sciences New Product Management ga Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_life_sciences_product_nudb.j2" dest="{{ mcs_conf_dir }}/answer_life_sciences_product.txt" mode=2777
  when: not update_database
  tags: 
    - ENOVIALIFESCIENCESManagement
    - install-apps-ga



- name: Executing the Life Sciences New Product Management ga installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_life_sciences_product.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIALifeSciencesAcceleratorforProductIntroduction.Unix64/1
  tags: 
     - ENOVIALIFESCIENCESManagement
     - install-apps-ga
   

- name: Remove the Life Sciences New Product Management ga Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_life_sciences_product.txt" state=absent
  tags: 
     - ENOVIALIFESCIENCESManagement
     - install-apps-ga
