---
 
- name: create symbolic link for the java 7 path
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - ENOVIAEBOMAVLManagement
  
  
- name: Copy the EBOMAVL Management Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_avl_mgt.j2" dest="{{ mcs_conf_dir }}/answer_bom_avl_mgt.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIAEBOMAVLManagement
    - install-mcs
    - install-apps-ga
   
- name: Copy the EBOMAVL Management Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_bom_avl_mgt_nudb.j2" dest="{{ mcs_conf_dir }}/answer_bom_avl_mgt.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIAEBOMAVLManagement
     - install-mcs
     - install-apps-ga

- name: Executing the EBOMAVL Management installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_bom_avl_mgt.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIAEBOMAVLManagement.Unix64/1
  tags: 
     - ENOVIAEBOMAVLManagement
     - install-mcs
     - install-apps-ga
   

- name: Remove the EBOMAVL Management Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_bom_avl_mgt.txt" state=absent
  tags: 
     - ENOVIAEBOMAVLManagement
     - install-mcs
     - install-apps-ga

