---

- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src="{{ java7_version_dir }}" dest="{{ mcs_java_path }}" owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags:
    - ENOVIARequirementsCentralFoundation
  
- name: Copy the Requirements Central Foundation Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_req_cen_foundation.j2" dest="{{ mcs_conf_dir }}/answer_req_cen_foundation.txt" mode=2777
  when: update_database
  tags: 
    - ENOVIARequirementsCentralFoundation
    - install-mcs
    - install-apps-ga
   
- name: Copy the Requirements Central Foundation Answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_req_cen_foundation_nudb.j2" dest="{{ mcs_conf_dir }}/answer_req_cen_foundation.txt" mode=2777
  when: not update_database
  tags: 
     - ENOVIARequirementsCentralFoundation
     - install-mcs
     - install-apps-ga

- name: Executing the Requirements Central Foundation installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh -installerPath {{ ds_installer_path }} < {{ mcs_conf_dir }}/answer_req_cen_foundation.txt
  args:
    chdir: /{{ mcs_apps_ga_installer }}/ENOVIARequirementsCentralFoundation.Unix64/1
  tags: 
     - ENOVIARequirementsCentralFoundation
     - install-mcs
     - install-apps-ga
   

- name: Remove the Requirements Central Foundation Answer file
  remote_user: monitor
  become: true
  file: path="{{ mcs_conf_dir }}/answer_req_cen_foundation.txt" state=absent
  tags: 
     - ENOVIARequirementsCentralFoundation
     - install-mcs
     - install-apps-ga

