---
- name: create the DB_clean dir or make sure it exist
  remote_user: monitor
  become: true
  file: 
    path: "{{ mcs_orphan_dir }}" 
    state: directory 
    owner: "{{plm_user}}" 
    group: "{{plm_group}}" 
    mode: "0755"
  tags: 
    - deploy_iteration_object
    - deploy_orphanfile_delete

- name: copy script iteration_object_clean
  template:
    src: iterationobjectclean.sh.j2
    dest: "{{mcs_orphan_dir}}/iterationobjectclean.sh"
    owner: "{{plm_user}}"
    group: "{{plm_group}}"
    mode: "0755"
  tags:
    - deploy_iteration_object

- name: cronjob for iteration_object_clean
  remote_user: monitor
  become: true
  cron: 
    user: "{{ plm_user }}"
    name: "Execute iterationobject_clean script"
    hour: 20
    weekday: 6
    job: "/bin/bash {{mcs_orphan_dir}}/iterationobjectclean.sh >> {{mcs_orphan_dir}}/iteration-cron-error.log 2>&1"   
  tags:
    - deploy_iteration_object

- name: Enable iteration_object_clean cron job
  remote_user: monitor
  become: true
  cron:
    user: "{{ plm_user }}"
    name: "Execute iterationobject_clean script"
    hour: 20
    weekday: 6
    job: "/bin/bash {{mcs_orphan_dir}}/iterationobjectclean.sh >> {{mcs_orphan_dir}}/iteration-cron-error.log 2>&1"
    state: present
    disabled: no
  tags:
    - enable_iteration_object_cron

- name: Disable iteration_object_clean cron job
  remote_user: monitor
  become: true
  cron:
    user: "{{ plm_user }}"
    name: "Execute iterationobject_clean script"
    hour: 20
    weekday: 6
    job: "/bin/bash {{mcs_orphan_dir}}/iterationobjectclean.sh >> {{mcs_orphan_dir}}/iteration-cron-error.log 2>&1"
    state: present
    disabled: yes
  tags:
    - deploy_iteration_object
    - disable_iteration_object_cron


###Orphan_file_delete###

- name: copy script orphanfiledelete
  template:
    src: orphanfiledelete.sh.j2
    dest: "{{mcs_orphan_dir}}/orphanfiledelete.sh"
    owner: "{{plm_user}}"
    group: "{{plm_group}}"
    mode: "0755"
  tags:
    - deploy_orphanfile_delete

- name: cronjob for orphanfiledelete
  remote_user: monitor
  become: true
  cron: 
    user: "{{ plm_user }}"
    name: "orphanfiledelete script"
    #hour: 20
    minute: "*/5"
    job: "/bin/bash {{mcs_orphan_dir }}/orphanfiledelete.sh >  {{mcs_orphan_dir}}/orphanfiledel-cron-error.log 2>&1"
  tags:
    - deploy_orphanfile_delete

- name: Enable cronjob for orphanfiledelete
  remote_user: monitor
  become: true
  cron:
    user: "{{ plm_user }}"
    name: "orphanfiledelete script"
    #hour: 20
    minute: "*/5"
    job: "/bin/bash {{mcs_orphan_dir }}/orphanfiledelete.sh >  {{mcs_orphan_dir}}/orphanfiledel-cron-error.log 2>&1"
    state: present
    disabled: no
  tags:
    - enable_orphanfile_delete_cron

- name: Disable cronjob for orphanfiledelete
  remote_user: monitor
  become: true
  cron:
    user: "{{ plm_user }}"
    name: "orphanfiledelete script"
    #hour: 20
    minute: "*/5" 
    job: "/bin/bash {{mcs_orphan_dir }}/orphanfiledelete.sh >  {{mcs_orphan_dir}}/orphanfiledel-cron-error.log 2>&1"
    state: present
    disabled: yes
  tags:
    - deploy_orphanfile_delete
    - disable_orphanfile_delete_cron



 
- set_fact: CronName="orphanfiledelete script" 
  tags:
   - status-orphanfile-delete-cron
     
- name: Orphanfiledelete Script Cron Status Check
  remote_user: "{{ plm_user }}"
  shell: crontab -l|grep -q "{{ CronName }}"&& printf ""||printf "NOTFOUND ";crontab -l|awk '/{{ CronName }}$/{f=NR}f&&NR==f+1'|cut -c 1|sed 's/#/DISABLED /;t;s/*/ENABLED  /;t;s/[0-9]/ENABLED  /;'
  register: cron_status
  tags:
   - status-orphanfile-delete-cron
   
- name: Orphanfiledelete Script Cron Status write in /tmp/cron_status @ ansible server
  local_action: shell echo  {{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }} >> /tmp/cron_status;
  tags:
   - status-orphanfile-delete-cron
   
- debug:
    msg: "{{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }}"
  tags:
   - status-orphanfile-delete-cron
   
   
   
- set_fact: CronName="Execute iterationobject_clean script" 
  tags:
   - status-iteration-object-clean-cron
     
- name: Execute Iterationobject_Clean Script Cron Status Check
  remote_user: "{{ plm_user }}"
  shell: crontab -l|grep -q "{{ CronName }}"&& printf ""||printf "NOTFOUND ";crontab -l|awk '/{{ CronName }}$/{f=NR}f&&NR==f+1'|cut -c 1|sed 's/#/DISABLED /;t;s/*/ENABLED  /;t;s/[0-9]/ENABLED  /;'
  register: cron_status
  tags:
   - status-iteration-object-clean-cron
   
- name: Execute Iterationobject_Clean Script Cron Status write in /tmp/cron_status @ ansible server
  local_action: shell echo  {{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }} >> /tmp/cron_status;
  tags:
   - status-iteration-object-clean-cron
   
- debug:
    msg: "{{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }}"
  tags:
   - status-iteration-object-clean-cron