---

#Create directory and instances [Tag: pre-task]
- include: create_dirs.yml
- include: install_java.yml
- include: install_instances.yml
- include: copy_config.yml


#Install MCS GA  
- include: install_live_collaboration.yml
- include: install_live_collaboration_fix_cas.yml
  when: not update_database

- include: install_business_process.yml
- include: install_multidis_collplat.yml
- include: install_3dexapps_mgt.yml
- include: install_collspace_mgt.yml


- include: install_studio_toolkit.yml
- include: install_3dlive.yml
- include: install_caddes_foundation.yml
- include: install_intex_framework.yml
- include: install_knowledge_std.yml
- include: install_eng_central.yml
- include: install_bom_conf_env.yml
- include: install_req_cen_foundation.yml
- include: install_prog_cen_foundation.yml
- include: install_prog_change_control.yml
- include: install_variantconf_central.yml
- include: install_enterprise_avl_mgt.yml
- include: install_bom_avl_mgt.yml
- include: install_cap_audit_foundation.yml
- include: install_comp_ncr_foundation.yml
- include: install_lib_central.yml
- include: install_prog_experience.yml
- include: install_conn_autocad.yml
- include: install_conn_solidworks.yml
- include: install_micro_proj_intrsrv.yml
- include: install_coll_microsoft_server.yml
- include: install_life_science_Product.yml
- include: install_dma.yml
- include: install_conn_CreoProENGINEERServer.yml





#Install MCS Fixpack  
- include: install_live_collaboration_fix.yml
  when: update_database
- include: install_business_process_fix.yml
- include: install_multidis_collplat_fix.yml
- include: install_3dexapps_mgt_fix.yml
- include: install_collspace_mgt_fix.yml


- include: install_studio_toolkit_fix.yml
- include: install_3dlive_fix.yml
- include: install_caddes_foundation_fix.yml
- include: install_intex_framework_fix.yml
- include: install_knowledge_std_fix.yml
- include: install_eng_central_fix.yml
- include: install_bom_conf_env_fix.yml
- include: install_req_cen_foundation_fix.yml
- include: install_prog_cen_foundationfx.yml
- include: install_prog_change_control_fix.yml
- include: install_variantconf_central_fix.yml
- include: install_enterprise_avl_mgt_fix.yml

- include: install_cap_audit_foundation_fix.yml
- include: install_comp_ncr_foundation_fix.yml
- include: install_lib_central_fix.yml

- include: install_conn_autocad_fix.yml
- include: install_conn_solidworks_fix.yml
- include: install_micro_proj_intrsrv_fix.yml
- include: install_coll_microsoft_server_fix.yml
- include: install_life_science_Product_fix.yml
- include: install_dma_fix.yml





- name: create symbolic link for java 7
  remote_user: monitor
  become: true
  file: src={{ java7_version_dir }} dest={{ mcs_java_path }} owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - set-java7
    
- name: create symbolic link for java 8
  remote_user: monitor
  become: true
  file: src={{ java8_version_dir }} dest={{ mcs_java_path }} owner={{ plm_user }} group={{ plm_group }} state=link force=yes
  tags: 
    - set-java8


#config change and compile [Tag: post-task]
- include: install_services.yml
- include: open_firewall.yml
- include: deploy_KOALA_config.yml
- include: deploy_mxenv_config.yml
- include: config_auth_passport.yml
  when: mcs_with_cas
- include: deploy_war.yml    
#- include: build_compile_code.yml
- include: build_compile_code_fix.yml   
- include: reg_in_passport.yml
  when: mcs_with_cas 
- include: show_env_name_to_login_window.yml 
- include: import_ssl_cert.yml
    
#Run index script
- include: run_mcs_search_index.yml
- include: run_partial_search_index.yml
- include: restart_services.yml
#- include: uninstall_mcs.yml
- include: dlt-license_bfr_export_v6_users.yml
- include: export_v6_users.yml
- include: backup_mcs_code.yml
- include: fcs_store_and_location_config.yml


- include: deploy_tidy_vault.yml
- include: copy_code_mcsnocas_mcscas.yml



###db clean###
- include: iterationobjclean.yml
- include: list_mql_user_product.yml
##
- include: mql_site_change.yml


## mql_command_fire
- include: mql_command_fire.yml
