---

- name: create the fts-cron dir
  remote_user: monitor
  become: true
  file: path="{{mcs_bin_dir}}/fts-cron" state=directory owner={{ plm_user }} group={{ plm_group }} mode=2777
  tags: 
   - run-partial-index
   
- name: Copy the script "run_partial_search_index.sh"
  template: src="script.partial.search.j2" dest="{{ mcs_bin_dir }}/run_partial_search_index.sh" owner={{ plm_user }} mode=0755
  tags: run-partial-index
  
- name: Copy the script "fts_cron_check.sh"
  template: src="fts_cron_check.sh.j2" dest="{{ mcs_bin_dir }}/fts_cron_check.sh" owner={{ plm_user }} mode=0755
  tags: run-partial-index
  
- name: Copy the script "fts_index_chk_script.sh"
  template: src="fts_index_chk_script.sh.j2" dest="{{ mcs_bin_dir }}/fts_index_chk_script.sh" owner={{ plm_user }} mode=0755
  tags: run-partial-index

- name: Setup Cron Job
  remote_user: monitor
  become: true
  cron: user={{ plm_user }} name="Execute partial search index" minute="*/5" job="/bin/bash {{mcs_bin_dir}}/run_partial_search_index.sh >> {{mcs_bin_dir}}/fts-cron/partial_index_status_$(date +'\%Y\%m\%d').log 2>&1"
  tags: run-partial-index

- name: Disable partial search index Cron Job
  remote_user: monitor
  become: true
  cron: user={{ plm_user }} name="Execute partial search index" minute="*/5" job="/bin/bash {{mcs_bin_dir}}/run_partial_search_index.sh >> {{mcs_bin_dir}}/fts-cron/partial_index_status_$(date +'\%Y\%m\%d').log 2>&1" state=present disabled=yes
  tags: 
   - disable-partial-index-cron
   
- name: Enable partial search index Cron Job
  remote_user: monitor
  become: true
  cron: user={{ plm_user }} name="Execute partial search index" minute="*/5" job="/bin/bash {{mcs_bin_dir}}/run_partial_search_index.sh >> {{mcs_bin_dir}}/fts-cron/partial_index_status_$(date +'\%Y\%m\%d').log 2>&1" state=present disabled=no
  tags: 
   - enable-partial-index-cron
 

 
- set_fact: CronName="Execute partial search index" 
  tags:
   - status-partial-index-cron
     
- name: Execute Partial Search Index Cron Status Check
  remote_user: "{{ plm_user }}"
  shell: crontab -l|grep -q "{{ CronName }}"&& printf ""||printf "NOTFOUND ";crontab -l|awk '/{{ CronName }}$/{f=NR}f&&NR==f+1'|cut -c 1|sed 's/#/DISABLED /;t;s/*/ENABLED  /;t;s/[0-9]/ENABLED  /;'
  register: cron_status
  tags:
   - status-partial-index-cron
   
- name: Execute Partial Search Index Cron Status Write in /tmp/cron_status @ Ansible Server
  local_action: shell echo  {{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }} >> /tmp/cron_status;
  tags:
   - status-partial-index-cron
   
- debug:
    msg: "{{ cron_status.stdout }},{{ plm_user }},{{ inventory_hostname }},{{  CronName  }}"
  tags:
   - status-partial-index-cron