---

- name: Check if Apps installer path exists
  win_stat: path="{{ apps_FP_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-fp
     - delmia-wordbook-fp
  
- name: Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-fp
     - delmia-wordbook-fp

- name: Copy delmia wordbook UserIntention file to target
  template: src="templates/user_intention_apps/fp/UserIntentions_Delmia_3dword.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_Delmia_3dword.xml"
  tags: 
     - install-app-fp
     - delmia-wordbook-fp

- name: Copy delmia wordbook installer from NFS to local
  win_copy:
    src: '{{ apps_FP_installer_path }}\DELMIA3DWorkbook.Windows64\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-fp
     - delmia-wordbook-fp
  
- name: Executing delmia wordbook installation on target
  win_psexec: 
      command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_fp_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_Delmia_3dword.xml --xmlreport {{windows_tmp_path}}\Report_del_word_fp.xml'
  tags: 
     - install-app-fp
     - delmia-wordbook-fp

- name: Removing the user Intension file for delmia wordbook from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_Delmia_3dword.xml" state=absent
  tags: 
     - install-app-fp
     - delmia-wordbook-fp
 
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-fp
     - delmia-wordbook-fp