---

- name: create the apps file storage  
  remote_user: monitor
  become: true 
  file: path="{{ apps_file_storage_dir }}" state=directory owner=root group=root mode="u=rwx,g=rx,o=rx"
  when: not env_name == 'preprod' and not fcs_type == "fcscentral"
  tags:
   - create_stores
   - install-fcs
   
- name: create the fcs mount dir  
  remote_user: monitor
  become: true 
  file: path="{{ fcs_store_mount_dest }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rx,o=rx"
  when: fcs_type == "fcscentral" and not is_1st_fcscentral == "yes" and not env_name == 'preprod'
  tags:
   - create_stores
   - install-fcs
   
- name: mounting FCS store to local
  remote_user: monitor
  become: true
  mount: name="{{ fcs_store_mount_dest }}" src="{{fcs_store_mount_source}}" fstype=nfs opts=defaults state=mounted
  when: fcs_type == "fcscentral" and not is_1st_fcscentral == "yes" and not env_name == 'preprod'
  tags: 
    - create_stores
    - install-fcs
   
- name: create the fcs file storage  
  remote_user: monitor
  become: true 
  file: path="{{ fcscentral_file_store_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rx,o=rx"
  when: fcs_type == "fcscentral"
  tags:
   - create_stores
   - install-fcs

- name: create the fcs file storage  
  remote_user: monitor
  become: true 
  file: path="{{ fcsremote_file_store_dir }}" state=directory owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rx,o=rx"
  when: fcs_type == "fcsremote"
  tags:
   - create_stores
   - install-fcs

- name: create apps file store
  remote_user: monitor
  become: true 
  file: path="{{ fcs_install_rel_path }}/stores" state=directory group={{ plm_group }} owner={{ plm_user }}  mode="u=rwx,g=rw" 
  tags:
   - create_stores
   - install-fcs

- name: create symbolic link
  remote_user: monitor
  become: true
  file: src="{{ fcscentral_file_store_dir }}" dest="{{ fcs_install_rel_path }}/stores" state=link owner="{{ plm_user }}" group="{{ plm_group }}" mode="u=rwx,g=rx" force=yes
  when: fcs_type == "fcscentral"
  tags:
   - create_stores
   - install-fcs
   
- name: create symbolic link
  remote_user: monitor
  become: true
  file: src="{{ fcsremote_file_store_dir }}" dest="{{ fcs_install_rel_path }}/stores" state=link owner="{{ plm_user }}" group="{{ plm_group }}" mode="u=rwx,g=rx" force=yes
  when: fcs_type == "fcsremote"
  tags:
   - create_stores
   - install-fcs

- name: creation stores
  remote_user: monitor
  become: true
  file: path="{{ fcs_install_rel_path }}/stores/{{ item }}" state=directory owner="{{ plm_user }}" group="{{ plm_group }}" mode="u=rwx,g=rx"
  with_items:
       - STORE
       - plmx
       - IMAGESTORE
  tags: 
   - create_stores
   - install-fcs
