---

- name: clear current java version or make sure dir is empty
  remote_user: monitor
  become: true
  shell: rm -rf {{ fcs_java_dir }}/*
  tags: 
   - install-java
   - install-fcs
  
- name: untar jdk 7 inside instance
  remote_user: monitor
  become: true
  unarchive: src="{{ java_installer }}" dest="{{ fcs_java_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  tags: 
   - install-java
   - install-fcs
   
- name: untar jdk 8 inside instance
  remote_user: monitor
  become: true
  unarchive: src="{{ java8_installer }}" dest="{{ fcs_java_dir }}" owner={{ plm_user }} group={{ plm_group }} copy=no mode="u=rwx,g=rw"
  tags: 
   - install-java
   - install-java8
   - install-fcs
 
- name: JAVA7 - GET JAVA7 DIRECTORY
  remote_user: monitor
  become: true
  command: find {{ fcs_java_dir }} -maxdepth 1 -type d ! -path {{ fcs_java_dir }} -iname "jdk1.7*"
  register: directoryJDK
  tags: 
   - install-java
   - install-fcs
   
- name: JAVA7 - LINKING
  remote_user: monitor
  become: true
  file: src={{ directoryJDK.stdout }} dest={{ fcs_java_dir }}/jdk-fcs state=link owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
  tags: 
   - install-java
   - install-fcs