---

- name: unarchiving tomcat 
  remote_user: monitor
  become: true
  unarchive: src="{{tomee_installer}}" dest="{{ fcs_instance_path }}" owner={{ plm_user }} group={{ plm_group }} copy=no 
  tags: 
   - install-instances
   - install-fcs
  
- name: create tomcat instances
  remote_user: "{{ plm_user }}"
  file: dest="{{fcs_instance_path}}/{{ item.key }}" state=directory 
  with_dict: "{{ instances }}"
  tags: 
   - install-instances
   - install-fcs

- name: copy tomcat content to instance
  remote_user: monitor
  become: true
  synchronize:
     src: "{{fcs_instance_path}}/{{ tomee_version }}/." 
     dest: "{{fcs_instance_path}}/{{ item.key }}" 
     checksum: yes 
     recursive: yes
     archive: no 
  delegate_to: "{{inventory_hostname}}"
  with_dict: "{{ instances }}"
  tags: 
    - install-instances
    - install-fcs

- name: remove tomcat version
  remote_user: monitor
  become: true
  file: path="{{fcs_instance_path}}/{{ tomee_version }}" state=absent
  tags: 
     - install-instances
     - install-fcs


- name: chage ownership
  remote_user: monitor
  become: true
  command: chown -R "{{plm_user}}":"{{plm_group}}" "{{fcs_instance_path}}/{{ item.key }}" 
  with_dict: "{{ instances }}"
  tags: 
    - install-instances
    - install-fcs
  
  
- name: create link for logs
  remote_user: monitor
  become: true 
  file: src="{{ fcs_log_dir }}/{{ item.key }}" dest="{{ fcs_instance_path }}/{{ item.key }}/logs" owner={{ plm_user }} group={{ plm_group }} state=link force=yes  
  with_dict: "{{ instances }}"
  tags: 
     - install-instances
     - install-fcs


- name: tomcat instance server.xml config
  remote_user: "{{ plm_user }}"
  template: src="tomee.server.xml.j2" dest="{{fcs_instance_path}}/{{ item.key }}/conf/server.xml"
  with_dict: "{{ instances }}"   
  tags: 
     - install-instances
     - install-fcs
  
- name: tomcat instance setenv.sh config
  remote_user: "{{ plm_user }}"
  template: src="tomcat.setenv.sh.j2" dest="{{fcs_instance_path}}/{{ item.key }}/bin/setenv.sh"
  with_dict: "{{ instances }}"
  tags: 
     - install-instances
     - install-fcs 
  
- name: Config tomcat user
  remote_user: "{{ plm_user }}"
  template: src="tomcat.users.xml.j2" dest="{{fcs_instance_path}}/{{ item.key }}/conf/tomcat-users.xml"
  with_dict: "{{ instances }}"
  tags: 
     - install-instances
     - install-fcs