---
- name: JAVA8 - GET JAVA8 DIRECTORY
  remote_user: monitor
  become: true
  command: find {{ fcs_java_dir }} -maxdepth 1 -type d ! -path {{ fcs_java_dir }} -iname "jdk1.8*"
  register: directoryJDK
  tags: install-fcsfx
   
#- name: JAVA8 - LINKING
 # remote_user: monitor
 # become: true
 # file: src={{ directoryJDK.stdout }} dest={{ fcs_java_dir }}/jdk-fcs state=link owner={{ plm_user }} group={{ plm_group }} mode="u=rwx,g=rw"
 # tags: install-fcsfx
   
   
- name: Check if FCS fixpack installer path exists
  stat: path="{{fcs_fixpack_installer}}"
  register: check_path
  tags: install-fcsfx


- name: FCS fixpack installer doesn't exist
  fail: msg="FCS fixpack installer doesn't exist!!"
  when: not check_path.stat.exists
  tags: install-fcsfx

   
- name: Copy the fcs fixpack answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer_fixpack.j2" dest="{{ fcs_install_rel_path }}/answer.txt" mode=2755
  tags: install-fcsfx


- name: Executing the FCS fixpack installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh < {{ fcs_install_rel_path }}/answer.txt
  args:
    chdir: /{{ fcs_fixpack_installer }}/1   
  tags: install-fcsfx


- name: Remove the Fixpack answer file
  remote_user: monitor
  become: true
  file: path="{{ fcs_install_rel_path }}/answer.txt" state=absent
  tags: install-fcsfx
