---

- name: Install NFS Server
  remote_user: "monitor"
  become: true
  yum: pkg=nfs-utils state=present
  

- name: Ensure rpcbind is running
  remote_user: "monitor"
  become: true
  service: name=rpcbind state=started enabled=yes
     
- name: Ensure NFS is running
  remote_user: "monitor"
  become: true
  service: name=nfs state=started enabled=yes

- name: Ensure nfs-share/mountable directory exists
  remote_user: "monitor"
  become: true
  file: path={{fcs_file_store_dir}} state=directory mode=0777

- name: copy update /etc/exports File
  remote_user: "monitor"
  become: true
  template: src=nfs_exports.j2 dest=/etc/exports owner=root group=root
     
- name: Restart NFS Server
  remote_user: "monitor"
  become: true
  service: name=nfs state=restarted 