---

- name: Check if FCS installer path exists
  remote_user: "{{ plm_user }}"
  stat: path="{{ fcs_installer_path }}"
  register: check_path
  tags: install-fcs


- name: FCS installer doesn't exist
  remote_user: "{{ plm_user }}"
  fail: msg="FCS installer doesn't exist!!"
  when: not check_path.stat.exists
  tags: install-fcs
 
 
- name: Copy FCS answer file to Installer Directory
  remote_user: monitor
  become: true
  template: src="answer.j2" dest="{{ fcs_install_rel_path }}/answer.txt" mode=2777
  tags: install-fcs


- name: Executing FCS the installation script.
  remote_user: "{{ plm_user }}"
  shell: ./StartTUI.sh < {{ fcs_install_rel_path }}/answer.txt
  args:
    chdir: /{{ fcs_installer_path }}/1   
  tags: install-fcs


- name: Remove the FCS answer file
  remote_user: monitor
  become: true
  file: path="{{ fcs_install_rel_path }}/answer.txt" state=absent
  tags: install-fcs

