---

- name: Check if Apps installer path exists
  win_stat: path="{{ apps_GA_installer_path }}"
  register: check_apps_path
  tags: 
     - install-app-ga
     - collaborative-ga
  
- name: Apps installer doesn't exist
  fail: msg="Apps installer doesn't exist!!"
  when: not check_apps_path.stat.exists
  tags: 
     - install-app-ga
     - collaborative-ga

- name: Copy collaborative task UserIntention file to target
  template: src="templates/user_intention_apps/ga/UserIntentions_colla_task_ga.xml.j2" dest="{{windows_tmp_path}}\UserIntentions_colla_task_ga.xml"
  tags: 
     - install-app-ga
     - collaborative-ga

- name: Copy collaborative task installer from NFS to local
  win_copy:
    src: '{{ apps_GA_installer_path }}\ENOVIACollaborativeTasksFoundation\1'
    dest: '{{ windows_tmp_path }}'
    remote_src: True
  tags: 
     - install-app-ga
     - collaborative-ga
  
- name: Executing collaborative task installation on target
  win_command: '{{windows_tmp_path}}\1\StartTUI.exe -installerPath {{ds_ga_installer_path}} --silent {{windows_tmp_path}}\UserIntentions_colla_task_ga.xml --xmlreport {{windows_tmp_path}}\Report_task_ga.xml'
  tags: 
     - install-app-ga
     - collaborative-ga

- name: Removing the user Intension file for collaborative task from traget
  win_file: path="{{windows_tmp_path}}\UserIntentions_colla_task_ga.xml" state=absent
  tags: 
     - install-app-ga
     - collaborative-ga
 
- name: Remove the installer folder.
  win_file: path="{{windows_tmp_path}}\1" state=absent
  tags:  
     - install-app-ga
     - collaborative-ga