---

# CA CRT to 3DDash-java
- name: Check if CA Certificate file exist or not
  stat: path="{{ dash_conf_dir }}/valmet-ca.crt"
  register: check_CA_crt_file
  tags: 
     - import-ca-crt
     - dash-post-task
  
- name: Copy CA Certificate file if not exist
  copy: src=valmet-ca.crt dest={{ dash_conf_dir }}/ owner={{ plm_user }} group={{ plm_group }} mode=0755
  when: check_CA_crt_file.stat.exists == false
  tags: 
     - import-ca-crt
     - dash-post-task
  
- name: Import CA Certificate to 3DDash-java 
  shell: keytool -importcert -keystore "{{ dash_ssl_keystore_path }}/cacerts" -noprompt -storepass {{ ssl_cert_pass }} -file valmet-ca.crt -alias "Valmet Issuing CA 1 Class 1"
  args:
    chdir: /{{ dash_conf_dir }}
  tags: 
     - import-ca-crt
     - dash-post-task


# 3DDash-instance CRT to 3DDash-java  
- name: Check if 3DDash-instance Certificate file exist or not
  remote_user: "{{ plm_user }}"
  stat: path="{{dash_conf_dir}}/{{env_name}}-dashinstance.crt"
  register: check_dashinstance_crt_file
  tags: 
     - import-dashinstance-crt
     - dash-post-task
  
- name: Copy 3DDash-instance Certificate file if not exist
  remote_user: "{{ plm_user }}"
  copy: src={{env_name}}-dashinstance.crt dest={{ dash_conf_dir }}/ owner={{ plm_user }} group={{ plm_group }} mode=0755
  when: check_dashinstance_crt_file.stat.exists == false
  tags: 
     - import-dashinstance-crt
     - dash-post-task
   
- name: Import 3DDash-instance Certificate to the server
  remote_user: "{{ plm_user }}"
  shell: keytool -importcert -keystore "{{ dash_ssl_keystore_path }}/cacerts" -noprompt -storepass {{ ssl_cert_pass }} -file {{env_name}}-dashinstance.crt -alias {{ ssl_dashinstance_cert_alias }} 
  args:
    chdir: /{{ dash_conf_dir }}
  tags: 
     - import-dashinstance-crt
     - dash-post-task
  
- name: Check if 3DDash-instance Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  shell: echo {{ ssl_cert_pass }} | keytool -list -v -keystore "{{ dash_ssl_keystore_path }}/cacerts" -alias {{ ssl_dashinstance_cert_alias }}
  register: check_dashinstance_crt_imp
  tags: 
     - import-dashinstance-crt
     - dash-post-task
  
- name: Check if 3DDash-instance Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  debug: msg="3DDash-instance Certificate imported successfully"
  when: check_dashinstance_crt_imp.stdout.find('Valid from') != -1
  tags: 
     - import-dashinstance-crt
     - dash-post-task


# 3DDash-ReverseProxy CRT to 3DDash-java
- name: Check if 3ddash Certificate file exist or not
  remote_user: "{{ plm_user }}"
  stat: path="{{ dash_conf_dir }}/{{env_name}}-3ddash.crt"
  register: check_dash_crt_file
  tags: 
     - import-dashproxy-crt
     - dash-post-task
       
- name: Copy 3ddash Certificate file if not exist
  remote_user: "{{ plm_user }}"
  copy: src={{env_name}}-3ddash.crt dest={{ dash_conf_dir }}/ owner={{ plm_user }} group={{ plm_group }} mode=0755
  when: check_dash_crt_file.stat.exists == false
  tags: 
     - import-dashproxy-crt
     - dash-post-task
     
- name: Import 3ddash Certificate to the server
  remote_user: "{{ plm_user }}"
  shell: keytool -importcert -keystore "{{ dash_ssl_keystore_path }}/cacerts" -noprompt -storepass {{ ssl_cert_pass }} -file {{env_name}}-3ddash.crt -alias {{ ssl_dash_cert_alias }} 
  args:
    chdir: /{{ dash_conf_dir }}
  tags: 
     - import-dashproxy-crt
     - dash-post-task
     
- name: Check if 3ddash Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  shell: echo {{ ssl_cert_pass }} | keytool -list -v -keystore "{{ dash_ssl_keystore_path }}/cacerts" -alias {{ ssl_dash_cert_alias }}
  register: check_dash_crt_imp
  tags: 
     - import-dashproxy-crt
     - dash-post-task
       
- name: Check if 3ddash Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  debug: msg="3ddash Certificate imported successfully"
  when: check_dash_crt_imp.stdout.find('Valid from') != -1
  tags: 
     - import-dashproxy-crt
     - dash-post-task  

# 3DPass CRT to 3DDash-java
- name: Check if 3dpass Certificate file exist or not
  remote_user: "{{ plm_user }}"
  stat: path="{{ dash_conf_dir }}/{{env_name}}-3dpass.crt"
  register: check_pass_crt_file
  tags: 
     - import-3dpass-crt
     - dash-post-task
       
- name: Copy 3dpass Certificate file if not exist
  remote_user: "{{ plm_user }}"
  copy: src={{env_name}}-3dpass.crt dest={{ dash_conf_dir }}/ owner={{ plm_user }} group={{ plm_group }} mode=0755
  when: check_pass_crt_file.stat.exists == false
  tags: 
     - import-3dpass-crt
     - dash-post-task
     
- name: Import 3dpass Certificate to the server
  remote_user: "{{ plm_user }}"
  shell: keytool -importcert -keystore "{{ dash_ssl_keystore_path }}/cacerts" -noprompt -storepass {{ ssl_cert_pass }} -file {{env_name}}-3dpass.crt -alias {{ ssl_pass_cert_alias }} 
  args:
    chdir: /{{ dash_conf_dir }}
  tags: 
     - import-3dpass-crt
     - dash-post-task
     
- name: Check if 3dpass Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  shell: echo {{ ssl_cert_pass }} | keytool -list -v -keystore "{{ dash_ssl_keystore_path }}/cacerts" -alias {{ ssl_pass_cert_alias }}
  register: check_pass_crt_imp
  tags: 
     - import-3dpass-crt
     - dash-post-task
       
- name: Check if 3dpass Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  debug: msg="3dpass Certificate imported successfully"
  when: check_pass_crt_imp.stdout.find('Valid from') != -1
  tags: 
     - import-3dpass-crt
     - dash-post-task
       
# MCS CRT to 3DDash-java  
- name: Check if mcs Certificate file exist or not
  remote_user: "{{ plm_user }}"
  stat: path="{{dash_conf_dir}}/{{env_name}}-3dspace.crt"
  register: check_mcs_crt_file
  tags: 
     - import-3dspace-crt
     - dash-post-task
       
- name: Copy mcs Certificate file if not exist
  remote_user: "{{ plm_user }}"
  copy: src={{env_name}}-3dspace.crt dest={{ dash_conf_dir }}/ owner={{ plm_user }} group={{ plm_group }} mode=0755
  when: check_mcs_crt_file.stat.exists == false
  tags: 
     - import-3dspace-crt
     - dash-post-task
       
- name: Import mcs Certificate to the server
  remote_user: "{{ plm_user }}"
  shell: keytool -importcert -keystore "{{ dash_ssl_keystore_path }}/cacerts" -noprompt -storepass {{ ssl_cert_pass }} -file {{env_name}}-3dspace.crt -alias {{ ssl_mcs_cert_alias }} 
  args:
    chdir: /{{ dash_conf_dir }}
  tags: 
     - import-3dspace-crt
     - dash-post-task
       
- name: Check if mcs Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  shell: echo {{ ssl_cert_pass }} | keytool -list -v -keystore "{{ dash_ssl_keystore_path }}/cacerts" -alias {{ ssl_mcs_cert_alias }}
  register: check_mcs_crt_imp
  tags: 
     - import-3dspace-crt
     - dash-post-task
       
- name: Check if mcs Certificate imported successfully or not
  remote_user: "{{ plm_user }}"
  debug: msg="mcs Certificate imported successfully"
  when: check_mcs_crt_imp.stdout.find('Valid from') != -1
  tags: 
     - import-3dspace-crt
     - dash-post-task
          