---

- name: Pre task 
  hosts: mcs_servers
  remote_user: monitor 
  sudo: true
  pre_tasks:
   - name: create dir for mount 
     file: path="{{ mount_dest_dir }}" state=directory
   - name: mounting NFS to local
     mount: name="{{ mount_dest_dir }}" src="{{ mount_src_dir }}" fstype=nfs opts=defaults state=mounted
     tags: mounting

- name: Create user
  hosts: mcs_servers
  remote_user: "monitor"
  sudo: true
  vars:
    studio_user: "plmm3ma"
    studio_group: "plm"
  roles:
      - { role: create-user, action: "create" ,  user_name: "{{ studio_user }}", user_pass: "{{ studio_user }}", group_name: "{{ studio_group }}" }
      
- name: Install 13x studio
  hosts: mcs_servers
  vars:
   plm_user: "plmm3ma"
   plm_group: "plm"
  remote_user: "{{ plm_user }}"
  sudo: false
  roles:
      - { role: studio  }	