---
# tasks file for wdijkerman.zabbix

- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Install the correct repository"
  include: "Suse.yml"
  when: ansible_os_family == "Suse"
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: "Fail invalid specified agent_listeninterface"
  fail:
    msg: "The specified network interface does not exist"
  when: "agent_listeninterface and (agent_listeninterface not in ansible_interfaces)"
  tags:
    - zabbix-agent
    - config

- name: "Get IP of agent_listeninterface when no agent_listenip specified"
  set_fact:
    agent_listenip: "{{ hostvars[inventory_hostname]['ansible_' + agent_listeninterface]['ipv4'].address | default('0.0.0.0') }}"
    agent_ip: "{{ hostvars[inventory_hostname]['ansible_' + agent_listeninterface]['ipv4'].address | default('0.0.0.0') }}"
  when: "agent_listeninterface and not agent_listenip"
  tags:
    - zabbix-agent
    - config
    - api

- name: "Default agent_listenip to all when not specified"
  set_fact:
    agent_listenip: '0.0.0.0'
    agent_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}"
  when: "not agent_listenip"
  tags:
    - zabbix-agent
    - config

- name: "Fail invalid specified agent_listenip"
  fail:
    msg: "The agent_listenip does not exist"
  when: "agent_listenip != '0.0.0.0' and agent_listenip not in ansible_all_ipv4_addresses"
  tags:
    - zabbix-agent
    - config

- name: "Configure zabbix-agent"
  template: src=zabbix_agentd.conf.j2
            dest=/etc/zabbix/zabbix_agentd.conf
            owner=zabbix
            group=zabbix
            mode=0755
  notify: restart zabbix-agent
  become: yes
  tags:
    - zabbix-agent
    - config
    - init

- name: "Create include dir zabbix-agent"
  file: path={{ agent_include }}
        owner=zabbix
        group=zabbix
        state=directory
  become: yes
  tags:
    - config
    - include
    - zabbix-agent

- name: modify user sudo privilege
  shell: echo "zabbix ALL=(ALL:ALL) ALL" | (EDITOR="tee -a" visudo)
  become: yes
  tags:
    - zabbix-agent

- name: "Install the correct userparameter"
  include: "userparameter.yml"
  tags:
    - zabbix-agent
    - init
    - config
    - service

- name: Allow zabbix-server ip in iptable rule
  command: iptables -I INPUT -p tcp -m tcp -s  {{ zabbix_server_ip }} --dport {{ zabbix_agent_port }} -j ACCEPT
  become: true
  when: ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - zabbix-agent  

- name: save iptables
  command: service iptables save
  become: true
  when: ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - zabbix-agent

- name: alow Iptables for RHEL7
  shell: firewall-cmd --add-port=10050/tcp --permanent
  become: true
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes
  tags:
    - zabbix-agent
  
- name: Reload Iptables for RHEL7
  shell: firewall-cmd --reload
  become: true
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes
  tags:
    - zabbix-agent

- name: "Make sure the zabbix-agent service is running"
  service: name=zabbix-agent
           state=started
  become: yes
  tags:
    - init
    - service
    - zabbix-agent

- name: "Create hostgroups"
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_group: "{{ zabbix_host_groups }}"
    state: "{{ zabbix_create_hostgroup }}"
  become: no
  when: zabbix_api_use
  tags:
    - api
    - zabbix-agent

- name: "Create a new host or update an existing host's with jmxport info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ tomcat_templates }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    interfaces:
      - type: 1
        main: 1
        useip: "{{ zabbix_useuip }}"
        ip: "{{ agent_ip }}"
        dns: "{{ ansible_fqdn }}"
        port: "{{ agent_listenport }}"
      - type: 4
        main: 1
        useip: "{{ zabbix_useuip }}"
        ip: "{{ agent_ip }}"
        dns: "{{ ansible_fqdn }}"
        port: "{{ port_jmx }}"
  become: no
  when: "with_jmx"
  tags:
    - api
    - zabbix-agent

- name: "Create a new host or update an existing host's without jmx info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ FTS_Template }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    interfaces:
      - type: 1
        main: 1
        useip: "{{ zabbix_useuip }}"
        ip: "{{ agent_ip }}"
        dns: "{{ ansible_fqdn }}"
        port: "{{ agent_listenport }}"
  become: no
  when: "fts"
  tags:
    - api
    - zabbix-agent

- name: "Create a new host or update an existing host's without 3dindextemplate info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ 3dindex_Template }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    interfaces:
      - type: 1
        main: 1
        useip: "{{ zabbix_useuip }}"
        ip: "{{ agent_ip }}"
        dns: "{{ ansible_fqdn }}"
        port: "{{ agent_listenport }}"
  become: no
  when: "3dindex"
  tags:
    - api
    - zabbix-agent


- name: "Updating host configuration with macros"
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
  with_items: zabbix_macros
  when: zabbix_api_use and zabbix_macros is defined and item.macro_key is defined
  tags:
    - api
    - zabbix-agent

