- name: Firing -> Run test script for 3dnotification
  win_command: '{{ installation_path_notification }}\win_b64\code\command\run_test.bat'
  register: outputListCommand
  tags: 
     - run_test
- name: Printing -> Run test output for 3dnotification
  debug: msg={{ outputListCommand  }}
  tags: 
     - run_test
